### ISSUE TITLE
Uncaught ReferenceError: eel is not defined

### ISSUE THREAD

**Issue by ayushmankumar7** [samuelhwilliams/Eel#136]
as i try to execute some Javascript command, this error pops up.

**Comment by samuelhwilliams** [comment]
Please can you provide samples of your code that will allow us to reproduce this error.

**Comment by cr4shcod3** [comment]
Did you include the eel.js in your HTML file?

**Comment by ayushmankumar7** [comment]
Obviously i did... It was a JavaScript error that popped up in my console

**Comment by robbiedvnn** [comment]
I am getting the same error. I have updated eel and pip. 

`function test_btn(e) {
  document.getElementById("btn_test").innerHTML = "Tested";
  var n = eel.whatsup()();
  console.log(n);
  document.getElementById("btn_test").innerHTML = n;
}`

The first line executes correctly. 

This is my python function.
`@eel.expose
def whatsup():
    print ("This came from python")
    return ("This came from python")
`

**Comment by 04fsnape** [comment]
@ayushmankumar7 @robbiedvnn does this happen with the demos?

**Comment by samuelhwilliams** [comment]
I'm going to close this due to inactivity.

**Comment by sajjadafridi** [comment]
eel is not defined  at index.html:9
same issue.

**Comment by sajjadafridi** [comment]
> as i try to execute some Javascript command, this error pops up.

Please check and confirm your path of eel.js and other js function. After experimenting a lot i executed

**Comment by jrcribb** [comment]
Without an example of your code we can't help you

**Comment by MrAbsurdick** [comment]
`import eel
import json


eel.init("GUI")

@eel.expose
def sendWebhook(hook):
    print(hook)


eel.start("index.html")`
`<script>
    async function call(){
        await eel.sendWebhook("Hello py")
    }
    call()
</script>`

Абсолютно тоже, при этом это старый код, раньше работал, возможно EEL переработан, по тому что даже сейчас если я хочу задать размеры окну в .py размер не выставляется, или обновлена браузерная система взаимодействий

**Comment by LudovicLambrechts** [comment]
I get the same kind of error "ReferenceError: eel is not defined at eel.js:1:5" error.

It does find the /eel.js file, but the Javascript console complains about of a missing "**const**/**let**/var" before the generated  **eel= {...}** code

**Comment by samuelhwilliams** [comment]
Would you mind sharing your code please?
