### ISSUE TITLE
eel.js:115 WebSocket connection to 'ws://localhost:8080/eel?page=index.html' failed: Connection closed before receiving a handshake response (anonymous) @ eel.js:115

### ISSUE THREAD

**Issue by lucasnewkirk** [samuelhwilliams/Eel#144]
Anytime I try to  start Eel, I get this error. I thought it was my code at first but then I tried the simplest example provided [here ](https://nitratine.net/blog/post/python-gui-using-chrome/) and I still received this error.

**Comment by ProHackTech** [comment]
I'm having a similar issue. For me it's: "500 Internal Server Error, Sorry, the requested URL 'http://localhost:8000/web' caused an error"

**Comment by ChrisKnott** [comment]
What OS and browser are you guys using?

**Comment by MishaTreedye** [comment]
> What OS and browser are you guys using?

Same issue. Windows 7, Google Chrome 80.0.3987.106 (64-bit)

**Comment by samuelhwilliams** [comment]
I'm going to close this based on the age of the thread. If anyone is still having this problem, please create a new issue and I'll investigate it as a priority. Please share code snippets to help reproduce the errors if possible.

**Comment by nosachamos** [comment]
I get this issue when Eel is overloaded / has lots of calls.

Opened a new issue. Eels just dies and can't recover.

https://github.com/ChrisKnott/Eel/issues/536
