### ISSUE TITLE
Input dictionary for Jinja2 templates.

### ISSUE THREAD

**Issue by rdobbs-cb** [samuelhwilliams/Eel#157]
A key use of Jinja2 templates in web apps is rendering templates with dynamic data.  It seems like Eel doesn't support this behavior, since the render function call is not made with any arguments. In contrast, flask allows arbitrary number and naming of input arguments.  It seems like the functionality that I want could be implemented by passing a single conventionally named argument to the render function call, and allowing the variable to be specified in eel.start call.  Since the argument can be a dictionary, this provides a high degree of user customization, while just requiring a few lines of code changes in eel.

**Comment by samuelhwilliams** [comment]
Hi @rdobbs-cb. You're definitely right; our current implementation of Jinja templating is very limited.

I'd like to address this. If you can kindly share your use-case, along with some examples, to help me gather concrete things that users want to do it would be really helpful. I'm going to close this issue, but will continue the broader discussion on https://github.com/samuelhwilliams/Eel/issues/217, which is basically a duplicate.
