### ISSUE TITLE
KeyError: 'chromeFlags'

### ISSUE THREAD

**Issue by weathon** [samuelhwilliams/Eel#158]
When I use ```
eel.start('index.html', mode='chrome-app', port=8080,cmdline_args=['--disable-http-cache', '--incognito'])```, it give me this error, but the document said use cmdline_args but not 'chromeFlags'

**Comment by samuelhwilliams** [comment]
I believe this issue has been resolved on the latest versions of Eel, so I'm going to close this off now.
