### ISSUE TITLE
Need Help with Displaying Data on Page 

### ISSUE THREAD

**Issue by soumilshah1995** [samuelhwilliams/Eel#162]
Question regarding Eel Python 

I have a simple code in python which returns random. numbers and its  is exposed to eel
i have a simple html page where i want to display this data
I am able to get the first sample but the  the next sample are updating on python shell but not on the website i have to manually left click and refresh it
 can someone help with this issue 

import eel
import random

eel.init('web')

@eel.expose
def random_data():

data = random.randint(0, 20)
print(data)
return data
eel.start('JumBo.html', size=(800, 800), block=False) # Start

while 1:
random_data()
eel.sleep(4)

===============================
    <script type="text/javascript">
    eel.random_data()(my_func);
      function my_func(x){
        console.log(x);
        var par = document.querySelector('.data');
        par.innerHTML = "Data" + x ;
      }
    </script>

**Comment by samuelhwilliams** [comment]
Hi @soumilshah1995 - are you still having a problem with this? Sorry for the slow reply. If you are, could you try upgrading to the latest version of Eel, and then sharing the code again (ideally formatted using GitHub codeblocks).

Thanks!

**Comment by soumilshah1995** [comment]
No, i think i solved it thanks for getting back

**Comment by samuelhwilliams** [comment]
Good to know!
