### ISSUE TITLE
Headers???

### ISSUE THREAD

**Issue by mythblaw** [samuelhwilliams/Eel#165]
I've looked everywhere but I didn't found a solution for this, is it possible to **change UserAgent header** _on_ `eel.start()` ??
Like:
> `eel.start('main.html', headers=["User-Agent":"eel"], size=(640,480))`
And, in javascript:
> `if (window.navigator.userAgent == 'eel') { console.log('is eel') }`

**Comment by mythblaw** [comment]
???

**Comment by ChrisKnott** [comment]
@mythblaw I don't think this is really possible, sorry. Eel doesn't control the browser part, it only runs a local webserver, and the user-agent is defined on the browser side

**Comment by mythblaw** [comment]
Oh, it's because this is _somehow possible_ on Electron since they use modified Chromium, i'm trying to make a desktop app and also can't remove the bottom left infobar from itself's Chrome UI even with '--disable-infobar' flag it appears. I don't have a solution for that...
anyways thanks for the help!

**Comment by ChrisKnott** [comment]
Oh right, yes, it is probably possible if you are using Electron

**Comment by samuelhwilliams** [comment]
You should be able to override the user agent, for Chrome, by passing `--user-agent "eel"` to `eel.start` via `cmdline_args`. Example:

`eel.start("hello.html", cmdline_args=["--user-agent=eel"])`

Other browsers may vary.

Does that work for you?
