### ISSUE TITLE
Browser by browser check and then direct

### ISSUE THREAD

**Issue by subins2000** [samuelhwilliams/Eel#174]
It would be great if there's a run method is to check if chromium exists, if not try electron, if not firefox, if not edge, if not finally open URL in browser.

Currently I'm using :

```python3
try:
    # try chromium/chrome
    eel.start('index.html')
except EnvironmentError:
    print('Chromium not found. Opening in browser')
    eel.start('index.html', options={'mode': 'default'})
```

**Comment by ChrisKnott** [comment]
I think this is best left in user space personally, but I think a full example/demo like your one would be useful for people

**Comment by samuelhwilliams** [comment]
I think this is best left to the user for now, handled as you have via exceptions.
