### ISSUE TITLE
Function timeout while calling Js function from python?

### ISSUE THREAD

**Issue by RahulBadenkal** [samuelhwilliams/Eel#182]
When I try calling a javascript function from inside python, I have noticed that if the javascript function takes more than ~10 seconds to execute then value returned to python is None, even though the js functions returns a non-null value (confirmed by printing it in console).
In situations where input size is small, js functions returns correctly to python.
Is there a setting I can change to increase this time limit, if this indeed is the issue?

**Comment by samuelhwilliams** [comment]
Hi @RahulBadenkal, sorry for the slow reply.

You're right - we do have a hard-coded limit of about 10 seconds for function execution at the moment. I think it's a fair idea to make this configurable. Although it's a slightly hacky implementation at the moment, it feels relatively easy to unblock you on this (hopefully it's not too late), so I'll go ahead and put a PR up to expose this as configuration for now.

**Comment by RahulBadenkal** [comment]
Thanks!
