### ISSUE TITLE
EEL with HTTPS/SSL?

### ISSUE THREAD

**Issue by fbenavides69** [samuelhwilliams/Eel#184]
Hi,

Is there a way to setup EEL to get up with a self signed certificate so we can have HTTPS?

Rgs!

**Comment by samuelhwilliams** [comment]
Eel is intended to run mostly as a local webserver, so traffic is staying on the same machine (i.e. not going through any external network). I don't think there should be much need for HTTPS, though I appreciate the general preference for encrypted communication.

Can you explain a little more about why you think you want or need this? Perhaps I'm missing something.

**Comment by samuelhwilliams** [comment]
I'm going to close this for now as I'm trying to get issues under control and I haven't heard back. But if you want to continue this discussion then please drop an update here.

Thanks for your interest in Eel. :)
