### ISSUE TITLE
perform action when window is closed

### ISSUE THREAD

**Issue by karlgrossmann** [samuelhwilliams/Eel#190]
First of all thanks for developing Eel. I'm currently working with it to create a clean UI for a python script getting information from an API and it is great! I appreciate your work.

So I'm using a session to connect with the API which has to be closed at the end. I implemented a logout button to interrupt the connection but there will be users who exit the program via the browsers exit button. Is it possible to catch this scenario and call a python function when a user closes the browser window? Would be pretty decent.

**Comment by ChrisKnott** [comment]
Yes, the `close_callback` option which is passed to `eel.start()` will be called when all browser windows are closed.
