### ISSUE TITLE
Can't keep up!

### ISSUE THREAD

**Issue by ChrisKnott** [samuelhwilliams/Eel#192]
Sorry everyone for the lack of updates and responses recently. I keep intending to put some time aside to clear the backlog but I never manage to get round to it and the issues keep stacking up, and the number of users keeps increasing. This package is now downloaded from pypi 12k+ times a month. I am very proud of this but unfortunately I have quite a busy and stressful job outside of programming which doesn't really afford me the time or emotional energy to manage this repo as well as it should be. 

This might sound stupid but, *what are you meant to do in this situation?* This must happen all the time that a personal project grows beyond what one person can manage...?

**Comment by samuelhwilliams** [comment]
Hey @ChrisKnott. I should have time to take this on, at least insofar as handling issues, managing releases and maintaining the project.

**Comment by yeongbin-jo** [comment]
Thank you @ChrisKnott. This project has helped me a lot.
