### ISSUE TITLE
OpenCV Window in EEL

### ISSUE THREAD

**Issue by CyberSinister** [samuelhwilliams/Eel#193]
Hey! I don't know how to start this topic but I guess the title speaks for itself.

I have a program that currently opens a new Window for the OpenCV webcam but instead, I want to show the live view from OpenCV to my EEL app. Is there a way?

**Comment by CyberSinister** [comment]
Anyone have any ideas?

**Comment by RahulBadenkal** [comment]
Is it possible to get the video as stream of bytes from openCV rather than letting it open in a Tkinter window? (Never used openCV, so not sure how it works)
Also can you give some code so we can reproduce the issue and try it out.

**Comment by RahulBadenkal** [comment]
Quick google search led me here: [http://www.chioka.in/python-live-video-streaming-example/](url)
Just check if that's what you want.

**Comment by RahulBadenkal** [comment]
Tried that above link, seemed to be working.

main.py
``` python
"""
Entry Point to The App
"""

import logging
import os
import sys
from tkinter import Tk, messagebox
import eel
from camera import VideoCamera
import base64
import time


def show_error(title, msg):
    root = Tk()
    root.withdraw()  # hide main window
    messagebox.showerror(title, msg)
    root.destroy()


def gen(camera):
    while True:
        frame = camera.get_frame()
        yield frame


@eel.expose
def video_feed():
    x = VideoCamera()
    y = gen(x)
    for each in y:
        # Convert bytes to base64 encoded str, as we can only pass json to frontend
        blob = base64.b64encode(each)
        blob = blob.decode("utf-8")
        eel.updateImageSrc(blob)()
        # time.sleep(0.1)


def start_app():
    # Start the server
    try:
        BASEDIR = os.path.dirname(os.path.abspath(__file__))
        web_dir = BASEDIR
        start_html_page = 'index.html'
        eel.init(web_dir)
        logging.info("App Started")

        options = {'host': 'localhost', 'port': 0}

        eel.start(start_html_page, options=options)
    except Exception as e:
        err_msg = 'Could not launch a local server'
        logging.error('{}\n{}'.format(err_msg, e.args))
        show_error(title='Failed to initialise server', msg=err_msg)
        logging.info('Closing App')
        sys.exit()


if __name__ == "__main__":
    start_app()

```

camera.py
```python
import cv2


class VideoCamera(object):
    def __init__(self):
        # Using OpenCV to capture from device 0. If you have trouble capturing
        # from a webcam, comment the line below out and use a video file
        # instead.
        self.video = cv2.VideoCapture(0)
        # If you decide to use video.mp4, you must have this file in the folder
        # as the main.py.
        # self.video = cv2.VideoCapture('video.mp4')

    def __del__(self):
        self.video.release()

    def get_frame(self):
        success, image = self.video.read()
        # We are using Motion JPEG, but OpenCV defaults to capture raw images,
        # so we must encode it into JPEG in order to correctly display the
        # video stream.
        ret, jpeg = cv2.imencode('.jpg', image)
        return jpeg.tobytes()
```
script.js
``` javascript
function py_video() {
    eel.video_feed()()
}


eel.expose(updateImageSrc);
function updateImageSrc(val) {
    getImgUrlFromB64Str(val);
    let elem = document.getElementById('bg');
    elem.src = "data:image/jpeg;base64," + val
}


function getImgUrlFromB64Str(base64Str) {
    let uint8Array = convertDataURIToBinary(base64Str); // Convert base64Str to Uint8Array Binary
    const blob = new Blob([uint8Array], {type: "img/jpeg"}); // Convert uint8Array to blob
    let url = webkitURL.createObjectURL(blob); // Convert blob to url
    let encodedUrl = encodeURIComponent(url); // Encoding the url
    return encodedUrl;
}


function convertDataURIToBinary(b64Str) {
    let raw = window.atob(b64Str);
    let rawLength = raw.length;
    let array = new Uint8Array(new ArrayBuffer(rawLength));
    for (let i = 0; i < rawLength; i++) {
        array[i] = raw.charCodeAt(i);
    }
    return array;
}
```
index.html
``` html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>OpenCV Webcam Live</title>
</head>
<script type = "text/javascript" src="eel.js"></script>
<script type = "text/javascript" src="script.js"></script>


<body>

 <h1>Video Streaming Demonstration</h1>
    <img id="bg" src="" alt="">

<button onclick="py_video()">Start feed</button>
</body>
</html>
```

**Comment by CyberSinister** [comment]
Thank You, I appreciate it.

**Comment by t-walker-wei** [comment]
> Tried that above link, seemed to be working.
> 
> main.py
> 
> ```python
> """
> Entry Point to The App
> """
> 
> import logging
> import os
> import sys
> from tkinter import Tk, messagebox
> import eel
> from camera import VideoCamera
> import base64
> import time
> 
> 
> def show_error(title, msg):
>     root = Tk()
>     root.withdraw()  # hide main window
>     messagebox.showerror(title, msg)
>     root.destroy()
> 
> 
> def gen(camera):
>     while True:
>         frame = camera.get_frame()
>         yield frame
> 
> 
> @eel.expose
> def video_feed():
>     x = VideoCamera()
>     y = gen(x)
>     for each in y:
>         # Convert bytes to base64 encoded str, as we can only pass json to frontend
>         blob = base64.b64encode(each)
>         blob = blob.decode("utf-8")
>         eel.updateImageSrc(blob)()
>         # time.sleep(0.1)
> 
> 
> def start_app():
>     # Start the server
>     try:
>         BASEDIR = os.path.dirname(os.path.abspath(__file__))
>         web_dir = BASEDIR
>         start_html_page = 'index.html'
>         eel.init(web_dir)
>         logging.info("App Started")
> 
>         options = {'host': 'localhost', 'port': 0}
> 
>         eel.start(start_html_page, options=options)
>     except Exception as e:
>         err_msg = 'Could not launch a local server'
>         logging.error('{}\n{}'.format(err_msg, e.args))
>         show_error(title='Failed to initialise server', msg=err_msg)
>         logging.info('Closing App')
>         sys.exit()
> 
> 
> if __name__ == "__main__":
>     start_app()
> ```
> 
> camera.py
> 
> ```python
> import cv2
> 
> 
> class VideoCamera(object):
>     def __init__(self):
>         # Using OpenCV to capture from device 0. If you have trouble capturing
>         # from a webcam, comment the line below out and use a video file
>         # instead.
>         self.video = cv2.VideoCapture(0)
>         # If you decide to use video.mp4, you must have this file in the folder
>         # as the main.py.
>         # self.video = cv2.VideoCapture('video.mp4')
> 
>     def __del__(self):
>         self.video.release()
> 
>     def get_frame(self):
>         success, image = self.video.read()
>         # We are using Motion JPEG, but OpenCV defaults to capture raw images,
>         # so we must encode it into JPEG in order to correctly display the
>         # video stream.
>         ret, jpeg = cv2.imencode('.jpg', image)
>         return jpeg.tobytes()
> ```
> 
> script.js
> 
> ```js
> function py_video() {
>     eel.video_feed()()
> }
> 
> 
> eel.expose(updateImageSrc);
> function updateImageSrc(val) {
>     let elem = document.getElementById('bg');
>     elem.src = "data:image/jpeg;base64," + val
> }
> ```
> 
> index.html
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <title>OpenCV Webcam Live</title>
> </head>
> <script type = "text/javascript" src="eel.js"></script>
> <script type = "text/javascript" src="script.js"></script>
> 
> 
> <body>
> 
>  <h1>Video Streaming Demonstration</h1>
>     <img id="bg" src="" alt="">
> 
> <button onclick="py_video()">Start feed</button>
> </body>
> </html>
> ```

I am using [Web Media API](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia) stream the webcam in page. I want to know which method is more efficient.

**Comment by wishvaRavindu** [comment]
hi i am having a small issue with closing the video stream that is being sent in to HTML page is there a way to close it. I have used the same exact code for my project, to stop the video stream i tried calling __del__ function through a button click but the opencv window doesn't close.
