### ISSUE TITLE
Save settings in EEL?

### ISSUE THREAD

**Issue by CyberSinister** [samuelhwilliams/Eel#194]
Hi! Let's say I have an application which has an option to change it's theme and other options but every time the app starts, these options reset. Is there a to save these settings? Like in cookies or cache or something?

**Comment by FutureLights** [comment]
@CyberSinister try using [localstorage](https://www.w3schools.com/jsref/prop_win_localstorage.asp). It should do exactly what you want. It works like a lot like a cookie, but I find it much easier to use. Plus it gives you more space to take advantage of.

**Comment by samuelhwilliams** [comment]
Thanks @FutureLights :)

**Comment by CyberSinister** [comment]
Thanks man. I really appreciate it.
