### ISSUE TITLE
Python functions running after app is closed on macOS

### ISSUE THREAD

**Issue by gcon97** [samuelhwilliams/Eel#197]
Hi,
When I run the following on Windows, everything runs as expected. When 'collectData()' is called, it will print the list while the application is running. 
However on my mac, when i run the same code, collectData() is not executed until after the application is closed.
Is there a fix for this?

> eel.init('web')
eel.start('smsempty.html', size=(ewidth, eheight), block=False)

> @eel.expose
def collectData(MSISDN, issue, dates, inc):
    inputlist = [MSISDN, issue, dates, inc]
    print(inputlist)

> while True:
    eel.sleep(10)

**Comment by samuelhwilliams** [comment]
@gcon97 did you get to the bottom of this yet?

If not, can you please provide the full code for what you're running (or at least code that we can easily put into files and run to reproduce the error).

Unfortunately what you've provided so far isn't really enough for us to test this and give you good feedback.

**Comment by samuelhwilliams** [comment]
I'm going to close this issue now based on inactivity.
