### ISSUE TITLE
Close a window

### ISSUE THREAD

**Issue by AndroidPatcher** [samuelhwilliams/Eel#198]
Hi so I've been trying to close a window on javascript working with eel, but `window.close()` doesn't seem to work, are there any other ways to make the window close or to terminate the eel process on javascript?

**Comment by samuelhwilliams** [comment]
`window.close()` seems to work for me - can you share your code please? It's very difficult to help if I can't reproduce the problem, and having your exact code will generally help there. :)

**Comment by AndroidPatcher** [comment]
@samuelhwilliams here :)
` <script>
      window.onload = function() {
        //when page loads execute this function
        swal({
          title: "Welcome",
          text: "You were successfully logged in!",
          icon: "success",
          button: "Thanks",
          closeOnClickOutside: false,
          closeOnEsc: false,
          closeOnEsc: false
        }).then(value => {
          //if button "ok" is clicked it returns true in the value variable and then closes the window if true
          console.log("closing");
          window.close();
        });
      };
    </script>`

**Comment by FutureLights** [comment]
I was able to fix this issue with this `window.open(\'\',\'_self\').close()` code, whic would replace the `window.close()` code.

**Comment by AndroidPatcher** [comment]
Thanks for the response @FutureLights, I tried adding `window.open('', '_self').close();` after `then(value => {` but I still get this error `Scripts may close only the windows that were opened by it.`

**Comment by FutureLights** [comment]
What browser are you using?

**Comment by AndroidPatcher** [comment]
Found it so instead of redirecting with javascript to my page which I couldn't close later I created a js function that replaced the href and opened a new window so I could then call the window.close() argument. Here is my function if anyone wants to use it:
```javascript
function Pospopup(URL, title) //?Function to open new window with same position of parent window
{
  let left = window.screenX; //takes left property of mainfile window
  let top = window.screenY; //takes left property of mainfile window
  window.open(URL, title, "width=800, height=600, top=" + top + ", left=" + left); //opens new window and sets the left and top property
}
```
the left and top var are just to keep the window in the same position as the previous one.
Anyway big thanks to @samuelhwilliams and @FutureLights for helping me out

**Comment by mdhuzaifapatel** [comment]
> Found it so instead of redirecting with javascript to my page which I couldn't close later I created a js function that replaced the href and opened a new window so I could then call the window.close() argument. Here is my function if anyone wants to use it:
> 
> ```js
> function Pospopup(URL, title) //?Function to open new window with same position of parent window
> {
>   let left = window.screenX; //takes left property of mainfile window
>   let top = window.screenY; //takes left property of mainfile window
>   window.open(URL, title, "width=800, height=600, top=" + top + ", left=" + left); //opens new window and sets the left and top property
> }
> ```
> 
> the left and top var are just to keep the window in the same position as the previous one. Anyway big thanks to @samuelhwilliams and @FutureLights for helping me out

Hi, I'm facing the same issue of not able to close the browser window.
will this soultion work? can u please how should I implement this
