### ISSUE TITLE
Disable Developer Options in Chrome-App

### ISSUE THREAD

**Issue by CyberSinister** [samuelhwilliams/Eel#200]
Hey! 
I'm using eel in "Chrome-app" mode. Is there a way to disable the developer tools and such?

**Comment by samuelhwilliams** [comment]
The likely way to do this is to pass a flag/switch to chrome when it gets run. You can specify the flags to pass through the `cmdline_args` argument to `eel.start`, eg `eel.start('hello.html', cmdline_args=['--disable-dev-tools'])`.

The flag mentioned above appears to have been deprecated, though, and from a quick google I don't see a clearly-supported way of disabling developer tools altogether in chrome, unfortunately.

**Comment by CyberSinister** [comment]
I see, welp. Thanks. I appreciate it.
