### ISSUE TITLE
ptyhon/pyinstaller : eel to exe tells me: ( filenotfounderror: [errno 2] no such file or directory: 'eel' ) in auto-py-to-exe-master 

### ISSUE THREAD

**Issue by BMarquiz** [samuelhwilliams/Eel#202]
ptyhon/pyinstaller : eel to exe tells me: ( filenotfounderror: [errno 2] no such file or directory: 'eel' ) in auto-py-to-exe-master ,or [ permission is denied in cmd ]>>> when I tried in cmd . my OS win32bit python3.7 #52

my command line is: pyinstaller -y -F -i "C:/Users/Broo/Desktop/Barq/barq.ico" --add-data "C:/Users/Broo/Desktop/Barq/web";"web/" -m eel --hidden-import win32com  "C:/Users/Broo/Desktop/Barq/pass.py".

my OS win32bit

python 3.7
Eel 0.10.4
pyinstaller 3.5

the project is designed to work with internet.

**Comment by ChrisKnott** [comment]
Your command should start with `python -m eel ...`

**Comment by BMarquiz** [comment]
@ChrisKnott Thank you very mach it's work correctly
