### ISSUE TITLE
Using eel for front end web apps as a python version of reactjs, vuejs and angularjs

### ISSUE THREAD

**Issue by Joetib** [samuelhwilliams/Eel#205]
I have fallen in love with eel. and seeing how anvil.works uses python for both front end and back end, I have been thinking of being able to use python to do just the same and be able to integrate it with any web server application/library(django, flask, etc).
Something that isn't just localhost and doesn't necessarily use ngrok.
Is there any plans of turning eel to be anything like a web frontend python library(reactjs)?
I sincerely don't love coding javascript for every front end i build and i believe most pythonistas don't as well.

**Comment by samuelhwilliams** [comment]
Hi @Joetib - at the moment I don't have any plans to extend Eel to support this kind of architecture ("Python on the frontend"); it's main use-case is to provide a bridge between the ease of creating UIs (HTML/CSS/JS ecosystem) and the power of Python for data processing (eg numpy/scipy/etc). 

Some other people have integrated Eel with different frameworks, e.g. [Django-Eel](https://pypi.org/project/django-eel/) if you want to be able to expose it beyond just localhost - but I don't believe Eel has been built with his in mind, so I would suggest careful thought if you go down that route.
