### ISSUE TITLE
Adding a custom app breaks eel's routes

### ISSUE THREAD

**Issue by n0emis** [samuelhwilliams/Eel#211]
**Eel version**
I am using eel 0.11.0 with python 3.8.

**Describe the bug**
When adding a own app, none of the routes that are required for eel to work are served anymore.

**To Reproduce**
Run the following code-snippet:
```python
app = bottle.Bottle()
eel.init('web', allowed_extensions=['.js', '.html'])

def onclose(page, sockets):
    pass

# This is not strictly neccesary to break eel, it even won't work without if.
@app.route('/<site>/')
def redirect_to_index(site):
    bottle.redirect('/{}/index.html'.format(site))

eel.start(
    close_callback=onclose,
    app=app)
```

**Expected behavior**
Even when specifying a custom app, bottle should still serve eel's own routes.

**Additional context**
This is related to the changes introduced in #203

**Comment by samuelhwilliams** [comment]
@n0emis you're absolutely right, it doesn't work!

I've got a patch that should fix this and I'll try to get it out tonight.

Note to self: need to get even just a few tests out for this ASAP.
