### ISSUE TITLE
call_back argument of start dont work

### ISSUE THREAD

**Issue by EkremDincel** [samuelhwilliams/Eel#215]
I am using Eel 0.10.4

My app.py is this:
````
import eel

def close_callback_func(path,sockets):
    print("hello")

eel.init('web')
eel.start('main.html',size = (1000,600),close_callback=close_callback_func)
````
Program works fine but when i close chrome tab , my ``close_callback_func`` dont work?

**Comment by samuelhwilliams** [comment]
It looks like this has been fixed in the latest version of Eel - please can you try upgrading to v0.11.1?

**Comment by samuelhwilliams** [comment]
I'm going to close this for now based on inactivity.
