### ISSUE TITLE
Supported python versions

### ISSUE THREAD

**Issue by samuelhwilliams** [samuelhwilliams/Eel#219]
Python 2.7 is going end-of-life at the end of this year, and I'd like to drop support for it from this library around the same time. At the moment, according to https://pypistats.org/packages/eel, approximately 10% of Eel's package downloads are from Python 2, 80% from Python 3, and 10% unknown. I'm not sure what the unknowns represent and need to look into this - if anyone knows, please do share.

At the same time I feel it makes sense to pragmatically come down on a minimum Python 3 minor version to support. This will help us make the most use of new language features and decrease the maintenance burden of additional code, but without alienating too many of our users.

The latest figures from pypistats above shows that 0.00% are using 3.2, 0.00% 3.3, 0.21% 3.4, and 2.94% 3.5. It feels reasonable to me, therefore, to start support from 3.5 - **possibly** even from 3.6 - but I'd like to give some time for anyone watching to help present good arguments to keep compatibility with these less-used versions.

Although I plan to drop support for Python 2.7 around the end of the year, I'm not working to the same schedule to drop any support for Python 3.x versions. So expect Python 3.2/3.3/3.4 to continue for the foreseeable - but keep posted with this thread.

Keen for input: @ChrisKnott @ahopkins @brumar

**Comment by pauliyobo** [comment]
Hello.
I'd vote for 3.6
Keeping the stats you posted in mind, I could conclude that eventually users will be switching from 3.5 to more recent versions. It could be a good idea to focus from 3.6, since most likely more users will be stopping to use 3.5, even if it will most likely happen in months if not years.

**Comment by samuelhwilliams** [comment]
I'm going to deprecate version 2 now and, as @pauliyobo suggested, also set support at v3.6 onwards for the next release (v0.13.0)
