### ISSUE TITLE
Connection lost when refresh page or go to another page

### ISSUE THREAD

**Issue by igrG** [samuelhwilliams/Eel#221]
I build exe with pyinstaller and on some PC I have trouble with refresh page or going to another page in my app using eel. if I open link in another tab in browser and no closing main tab all is working but it isn't good solution i think

**Comment by becurrie** [comment]
Is there any news or updates on this? I'm running into the same issue when attempting to travel to a different file that's available in my static web folder.

I have a `login.html` file and I want to move to `index.html` but application exits when doing so.

**Comment by mivendors2020** [comment]
I just refresh connection but I think this is not good solution :)
Simply if page is open more than 15 - 20 secs connection lost

**Comment by Malachov** [comment]
Try rewrite close_callback, eventhough do it only in develop?
Server will run after exit and same port may not working next run...

  ```
  if devel:
        directory = 'gui/src'
        app = None
        page = {'port': 8080}

        def close_callback(page, sockets):
            pass

    else:
        directory = 'gui/web_builded'
        close_callback = None
        app = 'chrome-app'
        page = 'index.html'

        eel.start(page, mode=app, close_callback=close_callback, host='localhost', port=8686, disable_cache=True)


```

**Comment by samuelhwilliams** [comment]
@igrG @becurrie @mivendors2020 this shouldn't be an issue any more - the latest version of Eel will try to reconnect when the connection is dropped.

If Eel is existing when you go to a new page in your app, you probably haven't included `eel.js` on that page.

I'm going to close this for now but let me know if there's any outstanding issues.
