### ISSUE TITLE
I cant use selenium and multiprocessing in eel :/ 

### ISSUE THREAD

**Issue by olrtan1** [samuelhwilliams/Eel#224]
**Describe the problem**
I am trying to use multiprocessing to open multiple windows
The whole problem is that it opens in the window for eel 
** error **
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('localhost', 8000)

**Code snippet(s)**

```python
import eel
from selenium import webdriver
from multiprocessing import Pool
import time

# Set web files folder and optionally specify which file types to check for eel.expose()
eel.init('web', allowed_extensions=['.js', '.html'])

@eel.expose                         # Expose this function to Javascript
def Open():
    if __name__ == '__main__':
        url_list = ['http://www.google.com', 'http://www.github.com', 'http://www.facebook.com', 'http://www.google.com',
                    'http://www.google.fr', 'http://www.amazon.com', 'http://www.ebay.com', 'http://www.youtube.com',
                    'http://www.google.com', 'http://www.python.com']
        pool = Pool(processes=2)
        ret = pool.map(parsing, url_list)
        for text in ret:
            print(text[:30])




def parsing(url):
    driver = webdriver.Chrome()
    driver.set_page_load_timeout(300)
    driver.get(url)
    text = driver.page_source
    time.sleep(12)
    driver.close()
    return text

eel.start('index.html')    # Start  , size=(300, 200)

```

```html
<!DOCTYPE html>
<html>
    <head>
        <title>Hello, World!</title>

        <!-- Include eel.js - note this file doesn't exist in the 'web' directory -->
        <script type="text/javascript" src="/eel.js"></script>
        <script type="text/javascript">

        eel.Open();  // Call a Python function

        </script>
    </head>

    <body>
        Hello, World!
    </body>
</html>
```

**Comment by samuelhwilliams** [comment]
Hi @olrtan1, sorry to hear you've having trouble.

I've just copied and pasted the code you shared (very helpful - thanks) but I can't reproduce the error you say you're having. All of the windows open as I'd expect them to, until each site has been visited.

Is it possible to were just running the code multiple times? Only one instance of Eel can be running at a time (unless you specify a different port for each to run on), but it doesn't appear to have any issues opening the sites from `url_list` in their own windows.

**Comment by awesome-arjun11** [comment]
Hi @olrtan1, looks like your script is trying to create another bottle server on port 8000.
Try enclosing **eel.start** with **if \_\_name\_\_ == '\_\_main\_\_'** so that it's not called repeatedly during imports. 

```python
if __name__ == '__main__':
	eel.start('index.html')
```

**Comment by samuelhwilliams** [comment]
I'm going to close this issue for now based on inactivity.
