### ISSUE TITLE
set_host undefined

### ISSUE THREAD

**Issue by luo1994** [samuelhwilliams/Eel#225]
**Describe the problem**
I want to use the previous react admin project on eel. How should I configure it

**Code snippet(s)**

```jsx
export const eel = window.eel
eel.set_host( 'ws://localhost:8080' )
```

**Comment by OkkarMin** [comment]
Hello @luo1994 could you share how you were able to overcome this issue?

**Comment by chenbuer** [comment]
> Hello @luo1994 could you share how you were able to overcome this issue?

Check `eel.js` is fetching correctly. You may not be getting this js file correctly
