### ISSUE TITLE
Can not install Eel

### ISSUE THREAD

**Issue by HorrifyingMonkey** [samuelhwilliams/Eel#227]
**Eel version**
Please state the version of Eel you're using. None

**Describe the bug**
Can not install Eel

**To Reproduce**
1. Go to 'cmd'
2. type 'pip install Eel'
3. See error

**Expected behavior**
Eel Installs!

**Screenshots**
https://pastebin.com/jCuATWs9

**Desktop (please complete the following information):**

**Additional context**
Trying to install 'Auto-py-to-exe' (uses this' and i was getting an error, I decided to install the 2 dependencies separately, 'pyinstaller' and this. Pyinstaller installed without an issue, but trying to install this causes an error.

**Comment by RahulBadenkal** [comment]
From the error msg. you posted it looks like you are using python3.8 on windows.
Not sure about the combatibility of eel with python3.8. (I use 3.6, it works fine with it).
Couple of things I can suggest is:
- Try creating a virtual env. and install the required packages there. (or)
- Use python 3.6 and try. (Make sure you install the version of eel that auto-py-to-exe requires.) (or)
- From 'SystemExit: error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2' in your error msg looks like you are missing some  Visual C++ Build Tools (just my guess), so try installing those seperately. I remember a year back I had the same issue and I had to install the whole MS Visual Studio (the build tools come packaged with it). But It's huge in size, so keep that as your last option.

**Comment by HorrifyingMonkey** [comment]
I'm not the best with this side of working with python, in regards to your suggestions:

- What do you mean by the virtual environment? Never used one before.
- If I were to install Python 3.6 would I have to uninstall 3.8?
- I installed VSC especially for this, I normally use PyCharm. What tools would i need to install? I've tried to look at youtube videos but I haven't found anything that helps with the error I'm getting

**Comment by RahulBadenkal** [comment]
- You can install more the one version of python without uninstalling others. You just have to specify which version of python to use before running your .py files
- If you use PyCharm, Then it's very simple to create a virtual env. Go to settings -> Project Interpreter -> New environment -> and choose which version of python to use.
Other way to create a virtual env. is to type couple of commands in cmd (you can google it)
- By VSC, i think you mean Visual Studio Code which is a different editor altogether. I was talking about Visual Studio.

**Comment by HorrifyingMonkey** [comment]
Changing the python version to 3.6.8 seemed to fix it.  I didn't have to do any of the other bits, apart from the virtual environment.


Thanks for your help :)
