### ISSUE TITLE
i cant't call python function in react.

### ISSUE THREAD

**Issue by luo1994** [samuelhwilliams/Eel#230]
![image](https://user-images.githubusercontent.com/27198984/71811064-c376b180-30ae-11ea-9913-25081b58be09.png)

**Comment by RahulBadenkal** [comment]
Did you expose say_hello_py python function to eel?
Please Upload a snippet of your code (both py and js/html files) otherwise it is hard to tell what's going wrong

**Comment by luo1994** [comment]
Because of the port problem, I have solved it. I just reconfigure it. Thank you
