### ISSUE TITLE
Using "0.0.0.0" as host

### ISSUE THREAD

**Issue by bribrah** [samuelhwilliams/Eel#232]
**Describe the problem**
I'm trying to use 0.0.0.0 as host because I want to be able to connect to the GUI from other computers on the same network. This works, but it is making the window that eel opens open to 0.0.0.0:3000/main.html , which doesn't load. Is there a way to override the address that eel opens when it opens its chromium window?
**Code snippet(s)**

```python
import eel
eel.start("main.html", host="0.0.0.0")
```

**Comment by wd77** [comment]
From the way I read browsers.py you could try not to give host="0.0.0.0" but the real local ip address you would want to bind to. 
E.g: `host="172.16.1.1"` could work, as browsers.py builds the string to open from this host variable.  
I have tried that, and it works as a work-around if you only want to bind to one specific address.

**Comment by bribrah** [comment]
The problem with doing it that way, is that after I compile with py-installer, its not easily modifiable in the case that the machines ip address changes. It would be better if I could set and forget instead of having to modify like a config file everytime the ip address changes.

**Comment by ChrisKnott** [comment]
I think right now, your best bet is to add some code to find out the local IP address before you pass it to `eel.start()` (there are several possible techniques here - https://stackoverflow.com/questions/166506/finding-local-ip-addresses-using-pythons-stdlib)

I'll try and read up on the standards about what the expected semantics are for using 0.0.0.0. We could maybe add a second cmdline parameter that is used for `open()`, while `host` is passed to bottle.

---

BTW - are you saying that the GUI works with multiple users? The websockets all work correctly? This isn't a use case we really thought about so I'm surprised it works at all!

**Comment by bribrah** [comment]
Yes the gui works across multiple users, and it's actually a very very useful use case (basically allows the gui to be sued on any computer on the same network). I went ahead and just forked the project and modified browsers to fix this issue. 

All I did was
```
for i, url in enumerate(start_urls, 0):
        start_urls[i] = url.replace("0.0.0.0", "localhost")
```
in open()

**Comment by samuelhwilliams** [comment]
Given that Eel is intended mostly for single-user applications (ie. isn't intended to be used across the network in the supported case), and it can be addressed by the developer with the custom code @ChrisKnott suggested, I'm going to close this as "out of scope" for now. Thanks for sharing your use case though.
