### ISSUE TITLE
'--start-fullscreen' does not make the app start in full screen

### ISSUE THREAD

**Issue by NiklasWilke** [samuelhwilliams/Eel#234]
`eel.start('main.html', cmdline_args=['--start-fullscreen'])`

My app still starts in normal size. Am i doing something wrong or is it a bug ?

**Comment by jrcribb** [comment]
The problem is that chrome will not start on fullscreen mode if another chrome windows is active for security reasons.
Try to close all chrome's windows and test your programa again

**Comment by NiklasWilke** [comment]
Tha
