### ISSUE TITLE
Incompatible with snowboy

### ISSUE THREAD

**Issue by baihua86** [samuelhwilliams/Eel#236]
**Describe the problem**
A clear and concise description of what you're trying to accomplish, and where you're having difficulty.

**Code snippet(s)**

```python
import eel

...
```

```html
<html>
   ...
</html>
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by samuelhwilliams** [comment]
Hi @baihua86. Could you please provide more information on exactly the problem you're having, so that we can get up to speed on the issue more quickly and hopefully help resolve the issue?
