### ISSUE TITLE
Changing window's size and position doesn't work

### ISSUE THREAD

**Issue by TheBdouilleur** [samuelhwilliams/Eel#238]
**Describe the problem**
I am trying to add a frontend, using Eel, to my Python app. I want the only browser window that the app opens to be of a certain size and position. Running below code opens a chrome window of the default size (the size of the las opened and modified window).
Please help!

**Code snippet(s)**

```python
import eel
eel.init('web', allowed_extensions=['.js', '.html'])
eel.start('main.html', geometry={'size': (200, 100), 'position': (50, 50)}) 

```

```html
<!DOCTYPE html>
<html>
  <head>
    <title class="title">Hello, World!</title>
    <script type="text/javascript" src="/eel.js"></script>
  </head>

  <body>
    Hello, World!
  </body>
</html>
```

**Desktop (please complete the following information):**
 - OS: Windows 10 ( version 1909 
 - Browser: Chrome
 - Chrome version: 79.0.3945.130

**Comment by Zeerti** [comment]
@TheBdouilleur Not sure why geometry isn't working in your example, but you could try this as an alternative

`eel.start('index.html', size=(1024, 768), position=(0,0))`

This is what I use in mine and it does it exactly as you expect it to

**Comment by TheBdouilleur** [comment]
Thank you @Zeerti, running `eel.start('index.html', size=(1024, 768), position=(0,0))` doesn't work either.
Maybe the problem is a setting on my system or on Chrome ?

**Comment by TheBdouilleur** [comment]
EDIT: I just tried running `eel.start('index.html', mode='edge', size=(1024, 768), position=(0,0))` but it doesn't work either.

**Comment by TheBdouilleur** [comment]
EDIT: It must have been a bug; I have once more tested it and it works just fine !

**Comment by samuelhwilliams** [comment]
@TheBdouilleur glad to hear it :)

**Comment by boumer7** [comment]
So how do you fix it?

**Comment by boumer7** [comment]
This is what worked: move your eel.init('web') in your __name__ == '__main__' to the top: 
```
class YourProgram:
    def does_sth():
       pass

if __name__ == '__main__'
    # my code was here, before eel.init()
     eel.init('web')
     eel.start('main.html', size = (640, 320), port = 3000)

```

**Comment by avdebor** [comment]
still have this problem, idk how to fix it

**Comment by Katrin0522** [comment]
i have thos problem too...

**Comment by smironh** [comment]
I think the problem is with the library itself

**Comment by noxing-1106** [comment]
Size specification does not work on macOS...

**Comment by GustJc** [comment]
Try to use mode="edge" or some other browser.

I got this problem and when I acessed the app from the localhost:8000 I found out that my chrome was throwing CSP errors and wasn't loading the .js files because I had recently installed the 'noscript' extension that blocks all but allowed .js files. So the eel.js file was not loaded and thus the window size was not set.

The eel application is still your browser and it'll have your installed extensions so that one thing to be carefull about.

**Comment by AmineDeflaoui** [comment]
For the following solution works :
- add **if __name__ == '__main__'** befor init.
- I forgot the   **<script type="text/javascript" src="/eel.js"></script>** in HTML

**Comment by AsareelDon** [comment]
I have the same problem even though I put if __name__  ==  '__main__: in my init

**Comment by GabrielMarRib** [comment]
I was able to fix this issue using  `window.resizeTo(700, 500);` in JavaScript. I hope I helped someone :)
