### ISSUE TITLE
eel.start() opens in browser ,need a app like window

### ISSUE THREAD

**Issue by smokersan1** [samuelhwilliams/Eel#239]
**Describe the problem**
You need better documentation , I can't find them . I need to open the app in a app like window , not localhost in browser.There are far better ways to provide web ui if I am using browser . 
Sorry if it's a silly request .
Any help will be appreciated .

**Desktop (please complete the following information):**
 - OS: [ubuntu]

**Comment by Zeerti** [comment]
I haven't tested it myself, but wouldn't electron do what you're asking? I'd consider looking into how to setup electron with eel.

**Comment by Obround** [comment]
The problem (I feel) on windows when it is using chrome is that the title bar of the window is custom made, which doesn't look amazing. As for the localhost problem, you can use the `--incognito` flag to make sure the app doesn't show up in chrome history.

**Comment by patter001** [comment]
for the eel_start are you passing in app_mode = True ?and for the mode are you specifying "chrome"...I use that for releases, and the "app_mode=None" for debug so that it goes to the typical browser

**Comment by Zeerti** [comment]
I haven't had any luck getting it to launch without all the browser overhead, granted I have only done it on systems that cannot have firefox or chrome installed on them due to work restrictions

**Comment by samuelhwilliams** [comment]
It sounds like Electron is what you're after. Hopefully the other comments here have helped.

I'm going to close this for now. If you need further help, though, please do reach out again.
