### ISSUE TITLE
After I packaged the code as an app, I ran with the following error

### ISSUE THREAD

**Issue by luo1994** [samuelhwilliams/Eel#240]
Traceback (most recent call last):
  File "eel_CRA.py", line 63, in <module>
  File "eel_CRA.py", line 37, in start_eel
  File "eel/__init__.py", line 104, in init
AssertionError: eel.expose() call contains '(' or '='
[60853] Failed to execute script eel_CRA
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

**Comment by samuelhwilliams** [comment]
Can you share your code please? It looks like you might have an invalid character in your `eel.expose` call(s).

**Comment by luo1994** [comment]
I tried to solve this problem and removed the assertion. I found that it was caused by init method looping to other JS files. Now it's packed and running successfully. Thank you very much, but the package generated by pyinstaller is a little large。

**Comment by samuelhwilliams** [comment]
Glad to hear it's resolved. Yes they tend to be a bit on the heavier side, but that's generally true for Python apps I find.
