### ISSUE TITLE
Error 404 file not found solution

### ISSUE THREAD

**Issue by axl3blaz3** [samuelhwilliams/Eel#241]
**Is your feature request related to a problem? Please describe.**
Error 404 file not found issue:

**Describe the solution you'd like**
Sometimes the cwd changes so we have to add import os ,os.chdir('/current/path')

**Describe alternatives you've considered**
I tried  upgrading eel,chrome and it didn't work for me and even while debugging all seemed fine but then i tried this.

I hope this will help clear confusion for some of the other's facing this issue.

**Comment by RahulBadenkal** [comment]
Can't replicate your issue. Downloaded your code from: [your repo](https://github.com/axl3blaz3/Eel-help) and commented out the os.childdir code but everything was still working fine.
I used python 3.6.8 and eel 0.12.2

**Comment by samuelhwilliams** [comment]
I'm going to close this based on inactivity and a report that this couldn't be reproduced. If you're still having problems, please feel free to reach out again.
