### ISSUE TITLE
Compiling eel into a single exe that uses extern config files

### ISSUE THREAD

**Issue by flopper123** [samuelhwilliams/Eel#242]
**Describe the problem**
In my program the user has the option to create their own config file(s) for the program.
I save/load/create them dynamically in a sub-folder in my "web" folder where the rest of the gui is located.
My problem is that whenever I try to compile it down to a single file using the --onefile and run it, the gui and the program will run just fine except that it has removed all the config files and it doesn't create new ones.
What is the best way to approach this problem?

I should mention that whever I compile it down without the --onefile flag everything works as intended.

**Code snippet(s)**
An example of when I write to a file:
```
with open(resource_path('./web/data/data.json'), 'w') as dataFile:
        json.dump(dataConfig, dataFile)

...
```

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome]
 - Version [e.g. 80.0]

**Comment by becurrie** [comment]
Your configuration files are probably placed in a local `AppData` folder somewhere on your machine.

It might be useful to try adding some debugging lines that print out directory locations, see where they actually lead to and if any files are present within them.

I use `PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))` in my project for the "root" dir, try debugging that while the app is running and explore that directory!
