### ISSUE TITLE
Would eel be suitable for a simple game like Tetris?

### ISSUE THREAD

**Issue by Swicegood** [samuelhwilliams/Eel#247]

**Comment by RahulBadenkal** [comment]
If all you want to make is a one off tetris game, then I suggest using pygame and be done with it. Or if you want to have nicer graphics around it then you can use javacript / html for display and the core logic in python which the js calls.
Usually python is a bit slow for making games but for a simple game like tetris, I don't think you will have an issue.
Love to hear others suggestions on it though!

**Comment by Swicegood** [comment]
Thank you. I have already written the logic of the game in python and I
wan't to add an html/javascript GUI to it.

**Comment by ChrisKnott** [comment]
If you know how to render the visuals in HTML and JS then I think it will be easy enough to do

**Comment by Swicegood** [comment]
I appreciate it I've now made good progress.
