### ISSUE TITLE
Discord Group is much required.

### ISSUE THREAD

**Issue by axl3blaz3** [samuelhwilliams/Eel#250]
**Is your feature request related to a problem? Please describe.**
Every problem can be discussed on a Discord group

**Describe the solution you'd like**
We would like to have Discord group where we can live chat and discuss our problems or grow the community and also be able to meet other developers that are also working with EEL.

Please make this happen 💯

**Comment by becurrie** [comment]
I second this request 👍

**Comment by samuelhwilliams** [comment]
I'll set one up this week, just having some trouble with Discord at the moment.

@ChrisKnott and I will be in it and support its existence, but I think we're hoping that there will be plenty of community involvement in helping people use Eel through there as unfortunately we've both become quite busy lately and had not as much time as desirable here.

**Comment by Thoufak** [comment]
Nice idea. However, I would personally prefer a Telegram chat.

**Comment by samuelhwilliams** [comment]
Hi all. Sorry for the slow action on this - but happy to finally bring some closure.

@Thoufak I think a Telegram chat is an interesting idea, and I like the open source/privacy-centred aspects of it. That said, I suspect a Discord or Slack is more user-friendly and has a better feature set for now.

@axl3blaz3 @becurrie I've created a Discord server [here](https://discord.com/invite/3nqXPFX) for now.

I'm open to revisiting this in the future if there's a general drive to move to something else.

@ChrisKnott FYI
