### ISSUE TITLE
Using bottle-sqlalchemy with eel

### ISSUE THREAD

**Issue by RahulBadenkal** [samuelhwilliams/Eel#253]
**Is your feature request related to a problem? Please describe.**
I am trying to set up sqlalchemy with bottle using the code found [here](https://github.com/iurisilvio/bottle-sqlalchemy). In order to access the database session, It must be kept as a argument for my functions which will be set via some decoratiors that act when bottle's route() gets initiated. But when my javascript calls the py function via eel I get the following error:

`
TypeError: query_db() missing 1 required positional argument: 'db'
2020-03-10T13:17:10Z <Greenlet at 0x52ddbe0: _process_message({'call': 2.7731503061517104, 'name': 'query_db', ', <geventwebsocket.websocket.WebSocket object at 0x0)> failed with TypeError
`

(see function 'show' in the link above to get an idea of what I am talking about)

which makes me belive that eel is bypassing the bottle routes (and all the associated decorators) and calling my function directly. Tried confirming it by writing a custom decorator (see func() in the repo liked below), when js calls query_db, func decorator is not getting executed.

Link to sample code [here](https://github.com/RahulBadenkal/eel-sqlalchemy-test)
How would I fix this?

**Comment by samuelhwilliams** [comment]
Hi @RahulBadenkal. Sorry for the **very** slow reply. Not sure if you worked this out already but the order of wrapping functions matters. You need to insert your decorator inside (closer to the function definition) than the `eel.expose` decorator.

For example, using example 01 with the following wrapper:

```python
def wrapper(fn):
    @wraps(fn)
    def _wrapper(*args, **kwargs):
        print("decorated")
        return fn(*args, **kwargs)

    return _wrapper
```

With the `@wrapper` inside (before) `@eel.expose`:
```python
@eel.expose                         # Expose this function to Javascript
@wrapper
def say_hello_py(x):
    print('Hello from %s' % x)
```

Results in:
```
sam:~/git/Eel/examples/01 - hello_world [master]$ python hello.py
decorated
Hello from Python World!
decorated
Hello from Javascript World!
```

But putting `@wrapper` outside `@eel.expose` like so:

```python

@wrapper
@eel.expose                         # Expose this function to Javascript
def say_hello_py(x):
    print('Hello from %s' % x)
```

leads to the JS side not using the wrapper:
```
sam:~/git/Eel/examples/01 - hello_world [master]$ python hello.py
decorated
Hello from Python World!
Hello from Javascript World!
```

I'm going to close this assuming you've either worked this out yourself already, or this helps. But if it doesn't, please feel free to comment and re-open. Thanks.
