### ISSUE TITLE
[eel + pyinstaller] FileNotFoundError: [Errno 2] No such file or directory eel.js 

### ISSUE THREAD

**Issue by jhyunetp** [samuelhwilliams/Eel#255]
**Eel version**
Please state the version of Eel you're using.
0.11.0

**Describe the bug**

 Error prevents me to start my app.

**To Reproduce**
Kindly unzip and auto-py-to-exe
[web.zip](https://github.com/samuelhwilliams/Eel/files/4316179/web.zip)

**Expected behavior**
Startup of my application

**Screenshots**
![image](https://user-images.githubusercontent.com/40058848/76385023-f8033400-63a3-11ea-9ed2-3c9bddf63102.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser chrome

**Additional context**

I think pyinstaller doesn't add eel.js. But I wasn't able to find why it doesn't add.
Let me know if you need some help on this issue.

** What I did to solve this 
It was my eel folder of output folder. (i.e output\app\eel)
![image](https://user-images.githubusercontent.com/40058848/76384474-4c0d1900-63a2-11ea-81ca-143b3ef6cba8.png)

I was able to solve this issue by manually adding  to eel folder from github eel folder
![image](https://user-images.githubusercontent.com/40058848/76384466-44e60b00-63a2-11ea-8eca-ec94bbea0eba.png)

Thank you,
Antonio

**Comment by RahulBadenkal** [comment]
Yes, you are correct. Pyinstaller can't find eel.js so you have to help it by saying pick eel.js from this location. There are 3 ways to do this:
1. If you are using auto-py-exe, then in the add datas place, add the location of eel.js (../site-packages/eel/eel.js)
2. Or, directly add that location under datas in the .spec file generated by pyinstaller.
3. Or, you could refer to eel's readme [here](https://github.com/samuelhwilliams/Eel#building-distributable-binary-with-pyinstaller). That handles all that automatically, so you won't have to worry about it.

**Comment by jhyunetp** [comment]
Third Option was very helpful for me.
But I guess many people can miss that option like me.
I think it is better to automate that process in pyinstaller as well. 
Like creating js script via python script.

**Comment by RahulBadenkalSarci** [comment]
Well, agreed. Ideally someone should write a pyinstall hook for eel and submit a PR to pyinstaller team.

**Comment by samuelhwilliams** [comment]
Thanks @RahulBadenkal for helping @jhyunetp get to the bottom of this problem. I'm going to close this issue off for now - but am going to look at proposing a hook for pyinstaller. It doesn't look too tricky.

**Comment by asdat3** [comment]
hey,
I am currently having the same issue,
Could someone be so kind to explain me, how the 3rd option is working :)
1st and 2nd wasnt doing anything :/

I dont realy get what you mean with refering.
Thank you so much,
Q. Schilling

**Comment by asdat3** [comment]
> hey,
> I am currently having the same issue,
> Could someone be so kind to explain me, how the 3rd option is working :)
> 1st and 2nd wasnt doing anything :/
> 
> I dont realy get what you mean with refering.
> Thank you so much,
> Q. Schilling

![blabla](https://user-images.githubusercontent.com/29544382/86397828-dad0d900-bca4-11ea-91d7-0f483eef4e00.PNG)

**Comment by samuelhwilliams** [comment]
Hi @asdat3. Rather than using pyinataller directly, please instead use 'python -m eel' to package your app.

We've submitted a pyinataller hook that should make this less error prone in the future, but it hasn't yet been made available in a release. It should be coming soon.

**Comment by asdat3** [comment]
Hi, @samuelhwilliams 
dont realy get it, what does the python -m eel command package? where to launch it?

**Comment by samuelhwilliams** [comment]
Could you open a new issue and include the code you're running and the command, etc? Then we can provide more help. Thanks!
