### ISSUE TITLE
AssertionError: eel.expose() call contains '(' or '='

### ISSUE THREAD

**Issue by barischrooneyj** [samuelhwilliams/Eel#26]
Hi my program is structured as follows where bundle.js is a file containing all of the JS frontend, including the contents of the file `app.js` which I have listed below.  I have also listed the other two files below. I get an error when running `python3 gui.py` as follows:

```
Traceback (most recent call last):
  File "gui.py", line 3, in <module>
    eel.init("dist")                     # Give folder containing web files
  File "/usr/local/lib/python3.6/site-packages/eel/__init__.py", line 60, in init
    assert rgx.findall(r'[\(=]', expose_call) == [], "eel.expose() call contains '(' or '='"
AssertionError: eel.expose() call contains '(' or '='
```

```
gui.py
dist
  |- index.html
  |- bundle.js 
```

``` javascript
// app.js

eel.expose(say_hello_js);
function say_hello_js(x) {
  console.log('Hello from ' + x);
}
say_hello_js('Javascript World!');
eel.say_hello_py('Javascript World!');
```

``` html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="/eel.js"></script>
  </head>
  <body>
    <div id="root"></div>
    <script type="text/javascript" src="bundle.js"></script>
  </body>
</html>
```

``` python
import eel

@eel.expose                         # Expose this function to Javascript
def say_hello_py(x):
    print("Hello from %s" % x)

if __name__ == "__main__":
    eel.init("dist")                     # Give folder containing web files
    say_hello_py("Python World!")
    eel.say_hello_js("Python World!")   # Call a Javascript function
    eel.start("index.html")             # Start (this blocks and enters loop)
```

**Comment by ChrisKnott** [comment]
@barischrooneyj

The way the library is designed at the moment, the python script needs to know the names of exposed js functions immediately after the call to eel.init('web').

This is before the browser process is even running. The slightly hacky solution to this at the moment is to statically scan through all text files in the directory and look for "eel.expose(???)" strings.

The problem with this is it assumes that the contents of those brackets is just the plain function name like "eel.expose(my_function)".

In reality it could be something like a lambda or anonymous function. This is why it forbids ( and = characters.

I will have to look into your issue in more detail in a few days but this is the reason for that error message.

**Comment by ChrisKnott** [comment]
@barischrooneyj did you manage to get this working? I can't recreate the error. I think bundle-js must be automatically making 'say_hello_js' anonymous in the beautify step.

**Comment by white41** [comment]
I got an error when trying to `expose` a `Vue` method like this: `eel.expose(this.print)`, which i guess shows up because of the dot (`.`). I solved it doing `print = this.print` and then passing the new `print` to `expose`, which is not elegant.
Amazing work @ChrisKnott, i started using eel a few weeks ago and it made my life easier, i commend you for this awesome doing!
