### ISSUE TITLE
Error trying to create more than one thread using spawn

### ISSUE THREAD

**Issue by WMoraes13** [samuelhwilliams/Eel#270]
**Describe the problem**
I'm trying to create multiple threads using eel.spawn inside a for loop, but sems that for loop freeze while the spawn thread are running.

How can i do to make that work?

**Code snippet(s)**

```python
import eel

                for x in dig:
                    eel.spawn(create_thread(y, x)) #---->the for loop stucks here
                    print(x)#-----this print are not printed
                eel.spawn(multi_bin_orders(create_thread))# and this new thread(out the for loop) is not create.
````
There is anyway to do that???

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by ChrisKnott** [comment]
It's impossible to know without seeing the code for ```create_thread()```

**Comment by WMoraes13** [comment]
> It's impossible to know without seeing the code for `create_thread()`

Create thread have a while inside...that runs
