### ISSUE TITLE
Redirects to an eel app possible?

### ISSUE THREAD

**Issue by alepodj** [samuelhwilliams/Eel#277]
**Describe the problem**
I have an app that needs to authenticate users via a an external API and which offers a redirect option back the requester URL(my eel app in this case). The work flow is like below:

1- eel app starts and loads the entry html on the web folder as usual but with `socket.getfqdn()` to ideally be able to allow access to the app from other devices(but mainly cause the API call doesnt allow `localhost` or `127.0.0.1` it needs an actual `hostname` for the redirect function)

**Code snippet(s)**

```python
import eel
eel.init('web')
eel.start('pages/loading.html', host=socket.getfqdn(), size=(1300, 1000), mode='custom', port=443)
...
```

2-App makes a request call to the API mentioned above to check if the user is authenticated and if not warn the user and provide a click button authenticate

3-On click a new URL is created and navigated to as per API requirements which prompts the user for credentials and upon success is designed to return back to the provided host in this case im providing the same host used to bring eel up via `socket.getfqdn()`. The host im trying this on has port `443` listening and open

The 2 things i tried and the 2 outputs:
------------------------------------------

1- If i use the same browser window that eel spawns the moment i navigate to the API the python script terminates without errors, in turn not being able to receive the API redirect

2- If i spawn a new browser window using python lib webbrowser the API redirect happens fine but upon returning to `FQDN:443`(Fully Qualified Domain Name) the connection fails with `ERR_SSL_PROTOCOL_ERROR`

Expected
----------

I guess i could be pushing this whole thing too far, was wondering if anyone has any insights, or even potentially avoiding python from ending after navigating to the API. Also that SSL error, would that mean no SSL certificate is being provided? If so can one be?

Any hints or potential solutions are welcome :)

EDIT: `The API redirect works and tested to another URL i made sure its not the API fault`

Cheers

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.x.x.x

**Comment by 2press** [comment]
You can try your first option again and set a custom `close_callback` function. Thereby, you can prevent that the app is closed, when you are doing an auth redirect, because the app only closes if no callback is provided, cf. https://github.com/samuelhwilliams/Eel/blobhttps://github.com/samuelhwilliams/Eel/blob/7041a072cba1769f5d096c1559fe1b7b1a844a54/eel/__init__.py#L328-L338

**Comment by alepodj** [comment]
Even with a callback app ends abruptly

**Comment by alepodj** [comment]
Thanks, your example works for me.
