### ISSUE TITLE
Can't change the port from default 8000

### ISSUE THREAD

**Issue by Mayank096** [samuelhwilliams/Eel#280]
Hi, 
I know this question has been asked before, but the proposed solution did not worked for me.

 
![Error](https://user-images.githubusercontent.com/20142735/79729491-fc0e6400-8308-11ea-8f0f-61d4b72e048a.png)

Issue:
I have two python files - file1. py and file 2.py and 2 html files file1.html and file 2.html respectively.
Even after i pass port parameter in eel, it always opens my html file (both) in port : 8000.
(In second file i tried using 'host': 'localhost' also)
Due to which i get an error "only one usage of each socket is permitted (localhost,8000)

Note: In my both python files i tried to set port number but still it did not work out.
          I even tried this : https://github.com/samuelhwilliams/Eel/issues/195
          I even disabled my firewall

Thanks

**Comment by ChrisKnott** [comment]
You must have a zombie python session running - check in task manager

**Comment by Mayank096** [comment]
> You must have a zombie python session running - check in task manager

No, there is no other python session running. I re-checked using command prompt (taskkill)

**Comment by RahulBadenkalSarci** [comment]
I tried in my system, it is opening correctly as per the passed port.
Try passing port 0, if it works then, as @ChrisKnott said you might have a process (python or something else) already running at 8000. If it doesn't then we will have to investigate further.

**Comment by RahulBadenkal** [comment]
I tried in my system, it is opening correctly as per the passed port.
Try passing port 0, if it works then, as @ChrisKnott said you might have a process (python or something else) already running at 8000. If it doesn't then we will have to investigate further.

**Comment by Mayank096** [comment]
@ChrisKnott @RahulBadenkal i upgraded my eel, after which i was able to use different ports.
Thanks for the help guys.
