### ISSUE TITLE
Uncaught SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by Atihinen** [samuelhwilliams/Eel#286]
**Eel version**
Eel==0.12.3

**Describe the bug**
Uncaught SyntaxError: Unexpected identifier eel.js:11

**To Reproduce**
1. Create hello world example
1. Launch application
2. See no hello from python
3. Open console from browser

**Expected behavior**
To not have syntaxerrors on eel.js

**Screenshots**
Let me know if needed

**Desktop (please complete the following information):**
 - OS: Rasbian
 - Browser chromium 
 - Version 22.0.1229.94

**Comment by RahulBadenkal** [comment]
Did you add `<script src="eel.js"></script>` in your html file?

**Comment by Atihinen** [comment]
@RahulBadenkal yes, that's why the error is visible and due to that I also get `eel not defined` since it can't evaluate the eel.js

**Comment by samuelhwilliams** [comment]
@Atihinen this sounds strange - can you please include all the relevant files for your example so we can reproduce this?

**Comment by samuelhwilliams** [comment]
I'm going to close this for now based on activity. If you're still having a problem, please feel free to reach out again.

**Comment by dviggiano** [comment]
Has anyone found a solution to this issue?
