### ISSUE TITLE
Help with Crashes and Using Pyinstaller to bundle

### ISSUE THREAD

**Issue by wwderw** [samuelhwilliams/Eel#288]
I'm running KDE Neon and I've got a python3 app that's mainly TKinter based with one menu item that uses eel..

The button works, but when I try to go back and use the rest of the TKinter app, it's frozen.  Only terminating the konsole that is running the process terminates the program.

The snippet for the function that I am running is here:

eel.init('web')
        
eel.start('index.html', size=(800,600), mode='firefox', block=False)

while True:
       eel.sleep(1.0)

The other question I had was how to bundle this using Pyinstaller when eel isn't the main main program?  I did try to bundle it using the same command listed in the readme and I also tried bundling it the way I used to without Eel and in both instances, I'm getting lib errors as not being bundled in.  

If I comment out Eel portion, it is fine, so it's something that I know I'm doing, or is it that Eel is designed to be by itself and not mixed in with TKinter or other widget toolkits?  Which could explain why the TKinter portion of the app freezes after Eel is called.

Now, I didn't expect to get any other results as far as the program freezing after I clicked to start the Eel portion, I was just wanting to make sure that I was on the right track with bundling.

Thoughts?

**Comment by samuelhwilliams** [comment]
Tkinter and Eel probably both want to control the main event loop - they aren't really designed to be used together (at least Eel certainly isn't). Sorry. This isn't a supported use-case and isn't really something that I think we'll be able to explore at the moment.
