### ISSUE TITLE
There is a way to disable developer tools?

### ISSUE THREAD

**Issue by jerearaujo03** [samuelhwilliams/Eel#292]
I've tried many chrome flags, but I can't disable developer tools.
Also, there is a way to make my app not run over chrome? Because in MacOS, when my app opens, there menu bar is from Chrome.

**Comment by ncotrb** [comment]
Hi, I have disabled the opening of the DevTools with Javascript. For Apple other key codes may have to be considered. The script must be included or linked in every HTML document:

```javascript
window.addEventListener("keydown", function(event) {
    if (event.keyCode == 116) {
        // block F5 (Refresh)
        event.preventDefault();
        event.stopPropagation();
        return false;

    } else if (event.keyCode == 122) {
        // block F11 (Fullscreen)
        event.preventDefault();
        event.stopPropagation();
        return false;

    } else if (event.keyCode == 123) {
        // block F12 (DevTools)
        event.preventDefault();
        event.stopPropagation();
        return false;

    } else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) {
        // block Strg+Shift+I (DevTools)
        event.preventDefault();
        event.stopPropagation();
        return false;
    }
});
```

Alternatively to Chrome, Electron can be used together with EEL. Electron offers a wide range of customization possibilities.

**Comment by ncotrb** [comment]
You can also disable the context-menu:

```javascript
window.oncontextmenu = function(event) {
    // block right-click / context-menu
    event.preventDefault();
    event.stopPropagation();
    return false;
};
```

**Comment by samuelhwilliams** [comment]
Hi @jerearaujo03 - disabling developer tools will be down to finding the right flag in the browser you're using. You can try workarounds like those posted above, but I'd probably question why you need to do this - and be careful arbitrarily disabling key presses/context menus as you might confuse some users. But if you're absolutely devoted to disabling developer tools and can't find a browser flag, you'll probably need to resort to something hacky like that.

I'm going to close this for now as there isn't much more advice I can offer that's related to Eel. Hope this is enough for you. :)

**Comment by coderhimanshu7** [comment]
> Hi, I have disabled the opening of DevTools with Javascript. For MacOS other key codes may have to be considered. The script must be included or linked in every HTML document:
> 
> ```js
> window.addEventListener("keydown", function(event) {
>     if (event.keyCode == 116) {
>         // block F5 (Refresh)
>         event.preventDefault();
>         event.stopPropagation();
>         return false;
> 
>     } else if (event.keyCode == 122) {
>         // block F11 (Fullscreen)
>         event.preventDefault();
>         event.stopPropagation();
>         return false;
> 
>     } else if (event.keyCode == 123) {
>         // block F12 (DevTools)
>         event.preventDefault();
>         event.stopPropagation();
>         return false;
> 
>     } else if (event.ctrlKey && event.shiftKey && event.keyCode == 73) {
>         // block Strg+Shift+I (DevTools)
>         event.preventDefault();
>         event.stopPropagation();
>         return false;
> 
>     } else if (event.ctrlKey && event.shiftKey && event.keyCode == 74) {
>         // block Strg+Shift+J (Console)
>         event.preventDefault();
>         event.stopPropagation();
>         return false;
>     }
> });
> ```
> 
> Alternatively to Chrome, Electron can be used together with EEL. Electron offers a wide range of customization possibilities.

Thanks it worked for me on windows

**Comment by coderhimanshu7** [comment]
Thanks @ncotrb It worked for me

**Comment by anay-p** [comment]
I made the code that disables the shortcut keys more concise (and removed the deprecated keyCode part):
```javascript
var disabledKeys = ["F5", "F11", "F12"]
var disabledModifierKeys = ["I", "J"]
document.addEventListener("keydown", (event) => {
    if (disabledKeys.includes(event.key)
    || (event.ctrlKey && disabledModifierKeys.includes(event.key))) {
        event.preventDefault();
        event.stopPropagation();
    }
});
```
To block any other keys, just add to the list. Also, the key value for a keydown event is in lowercase when a letter is pressed but in uppercase when the shift key is also being pressed so there is no need to check for `event.shiftKey`.
