### ISSUE TITLE
Eel with ability to make push notifications within js 

### ISSUE THREAD

**Issue by yusuf8ahmed** [samuelhwilliams/Eel#293]
I've played around with Eel a little bit and it is amazing!

I'm building a personal app and I wanted the ability to create custom push notifications in javascript. I have the whole system built but I think this feature would be very beneficial for the broader Eel community

I am willing to personally work on the PR for this feature. Can I get some guidance or advice on how to proceed? Appreciate it!

![o7ja4 1](https://cloud.githubusercontent.com/assets/7101452/19763806/75f71ba4-9c5d-11e6-9f16-d0d4bf43e63e.png)

**Comment by ncotrb** [comment]
Hi, modern browsers support desktop notifications using Javascript. Keep in mind that user must explicitly agree to these notifications. Here is a good example script:
https://developer.mozilla.org/en-US/docs/Web/API/notification#Examples

Alternatively you could search for a Python library:
https://www.devdungeon.com/content/windows-desktop-notifications-python
