### ISSUE TITLE
Having trouble passing <input type="file> object to python

### ISSUE THREAD

**Issue by nizarcan** [samuelhwilliams/Eel#301]
In my project, I have a custom database which I pickle/update/unpickle when needed. From local webserver, I select the file and click the submit button. Then I pass the file directory to later read in python script. The structure I have is as follows;

**HTML**
I have two simple elements, one button and one input
```
<input type="file" id="file-upload">
<input class="btn btn-success" type="submit" onClick="get_input_directory()" value="Send">
```
**JS**
```
function get_input_directory() {
	var data = document.getElementById("file-uploader").value
	eel.get_input(data)
}
```
**Python**
And for the moment I just print the directory to see If I got it right.
```
@eel.expose
def get_input(data):
    print(data)
```
And what I planned to do later was to use the script down to unpickle database into my program:
```
with open(file_dir, "rb") as f:
    mdl = pickle.load(f)
    return mdl
```
But my database file is printed as:
```
C:/fakepath/database.file
```
I searched the web and found out that this is a security measure that browser implemented but I tried FileReader method to pass the file directly into the unpickling function but that also failed saying that no such file exists.

What should I use for this problem, or is there a way to pass the directory into the python script which would be much easier since the backend is pretty much done for project. Any help is appreciated. Thanks in advance!

  [1]: https://github.com/samuelhwilliams/Eel

**Comment by RahulBadenkal** [comment]
Well as you figured browser can't give you the complete path.
What you can do is use python's Tkinter library for the file dialogue box rather than the browser's. Doing it this way will give you the whole filepath.
So :
- On clicking something on UI (a button or something) -> Trigger a javascript function that triggers a python function.
- The python function makes use of Tkinter library and opens a file dialogue box. The user selects the file and clicks Ok.
- The python function resumes and returns this path (complete path) to the browser again (to the caller function in js)
- Then (if you want) display the filepath in the broswer and do whatever you need to do.

**Comment by nizarcan** [comment]
First of all, thanks for your response and taking your time. I thought that I found a solution but I faced another problem. I read the file with javascript(with FileReader API) and then passed it to python with base64 and unpickled after decoded the file. 

But I designed the filesystem to be multi-paged(i.e. when you fed the database into the program, the main menu would appear) but when I changed the webpage from let's say `login.html` to `index.html`, with javascript method `document.location.href = "index.html"`, the program automatically closes with exit code 0. 

To avoid this I, ran the `eel.start` function with `block=False`, but then the `login.html` did not even opened in the first place. Whenever I use `block=False`, I get the error `localhost refused to connect.`  , `ERR_CONNECTION_REFUSED`. The only other option that I use with `eel.start` function is `port=0` to automatically select another open port when another webpage is opened. 

How do I resolve this problem, what should I do to change the webpage, or initialize with `block=False` properly? If eel was designed for single-paged interfaces, I would have to give up on  eel altogether. Thanks a ton for your response in advance, hope you have a healthy and fantastic day, cheers!

**Comment by RahulBadenkal** [comment]
Usually I use front-end frameworks that handle navigating between different html pages. 
I personally dont know how to solve your problem but I remember someone raised an issue regarding what you are facing. Can you browse the old issues in this repo and check it out.

**Comment by nizarcan** [comment]
I resolved the problem by using the code below;
```
def ask_file(file_flags):
    # file_flags consists of tuple of tuples, i.e. (("jpeg files", "*.jpg"), ("all files", "*.*))
    root = Tk()
    root.withdraw()
    root.wm_attributes("-topmost", 1)
    file_path = filedialog.askopenfile(initialdir=os.path.expanduser("~/Desktop"), title="Select File",
                                       filetypes=file_flags)
    return file_path

```
Also, the problem about program crashing down when navigated to a different page than which initially opened, It got resolved as itself, I do not know what happened, may be it's the new update but I could not find the fix in the changelog of the update. But I guess it's fixed now. Since now both of my problems are resolved, I am closing this issue but I hope that the developer properly address this problem.

**Comment by willm** [comment]
Thanks to @nizarcan, I had to modify the code slightly and return the name property

```python
import eel
from tkinter import Tk, filedialog
import os

@eel.expose
def ask_file(file_flags):
    # file_flags consists of tuple of tuples, i.e. (("jpeg files", "*.jpg"), ("all files", "*.*))
    root = Tk()
    root.withdraw()
    root.wm_attributes("-topmost", 1)
    file_path = filedialog.askopenfile(
        initialdir=os.path.expanduser("~/code/rubix/embeddings"),
        title="Select File",
        filetypes=file_flags,
    )
    return file_path.name
```

then in js I called it like this

```javascript
  eel.ask_file([["csv files", "*.csv"]])((filePath) => doSomethingWithThePath(filePath));
```
