### ISSUE TITLE
Help wanted with hyperlinkslinks

### ISSUE THREAD

**Issue by LonaExe** [samuelhwilliams/Eel#306]
Hey, I want to know whether we can use Hyperlinks with Eel, and if yes, how?
This is my directory structure..
App.py
Web.py
  one.html
  two.html

I want to start at one.html and hyperlink to two, this works fine, but for some reason, I am not able to call App.py functions from two.html

 - windows
 - chrome.1

**Comment by ChrisKnott** [comment]
Yes, this should work. Did you remember to include eel.js on the second page?

**Comment by LonaExe** [comment]
Yes that was it. Thanks 😅😅
