### ISSUE TITLE
How to use close_callback?

### ISSUE THREAD

**Issue by SaranSundaresan** [samuelhwilliams/Eel#307]
HI. When I close my existing eel window, the python program still remains executing. Moreover, the localhost instance still remains active. I need to find a way to close the localhost instance and also the python program, if required, at the same time that I close the eel window. 

I believe **close_callback** will help me accomplish the above objective. But I'm getting the syntax wrong and I'm unable to understand the syntax well enough from the doc. Pls help!

**Comment by std-odoo** [comment]
If you want to close the application when you close the window, here is the syntax :)

```python
import eel


def close_callback(route, websockets):
    if not websockets:
        exit()


eel.init("web")
eel.start("main.html", close_callback=close_callback)
```


web/main.html
```html
<html>
    <body>
        <script type="text/javascript" src="/eel.js"></script>
        <div>bouh</div>
    </body>
</html>
```

The function `close_callback` takes 2 arguments
- the opened URL
- the remaining sockets (if you opened the page in many windows)

Hope it helps

**Comment by samuelhwilliams** [comment]
@SaranSundaresan this really shouldn't be happening if you're running the latest version of Eel. Can you share your code, your Python version, and Eel version?

The close callback that @std-odoo kindly shared should already be the default behaviour: https://github.com/samuelhwilliams/Eel/blob/bb058329b64b2f3e8d3e5d0e8a4cd6f3d3eab3b7/eel/__init__.py#L330-L340

**Comment by samuelhwilliams** [comment]
I'm going to close this based on inactivity - but please reach out if you're still having issues.

**Comment by matheus-delazeri** [comment]
Hi, I'm facing the same issue that @SaranSundaresan had. There's any solution already? 
`Python Version: 3.8.5` `Eel Version: 0.14.0`

Thanks in advance!

**Comment by matheus-delazeri** [comment]
Hi, I'm facing the same issue that @SaranSundaresan had. There's any solution already? 
`Python Version: 3.8.5` `Eel Version: 0.14.0`
My code:

main.py
```python
import eel

eel.init("web")
eel.start("index.html")
```

web > index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
</head>
<body>
    <p>Hello World!</p>
</body>
</html>
```

Thanks in advance!
