### ISSUE TITLE
ModuleNotFoundError: No module named 'eel'

### ISSUE THREAD

**Issue by Prskriti** [samuelhwilliams/Eel#314]
**Eel version**
Eel  0.12.4    

Not able to import Eel module in my python script.
 - OS: iOS
 - Browser:  chrome

Please find the snapshot below for more details:
<img width="1160" alt="Screen Shot 2020-06-12 at 5 03 01 PM" src="https://user-images.githubusercontent.com/26160349/84498779-eac15280-acce-11ea-9397-b4d2b8b65e5e.png">

**Comment by samuelhwilliams** [comment]
Hi @Prskriti - did you get to the bottom of this? I suspect it's a path resolution problem with rasa (I'm not familiar with it though). It doesn't seem to be directly related to Eel.

**Comment by Prskriti** [comment]
okay, @samuelhwilliams I will look into this. 
Thanks for ur response
