### ISSUE TITLE
WinError 10048 whenever i run eel 

### ISSUE THREAD

**Issue by cameronduncan678** [samuelhwilliams/Eel#315]
Hi there.  Im having a problem getting eel to run.  Everytime i run the app it keep generating  a: 

`OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted: ('localhost', 8000)`

When it opens it keeps saying:
```
This localhost page can’t be foundNo web page was found for the web address: http://localhost:8000/main.html
HTTP ERROR 404
```
Not sure whats causing it to do this.  Ive just been testing with a simple code: 
python

`import eel
eel.init('web')
eel.start('main.html')`

html
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>app</title>
    <script type="text/javascript" src="/eel.js"></script>
</head>
<body>
	This is a test
</body>
```
Any help would be much appreciated, thanks.

**Comment by samuelhwilliams** [comment]
Some other process is open on port 8000. You'll need to find it and kill it (it may be an old Eel process that didn't shut down correctly, or something else you're running already on port 8000).
