### ISSUE TITLE
Multiple pages with eel

### ISSUE THREAD

**Issue by felipexlr50** [samuelhwilliams/Eel#335]
Hi, I started recently in eel, and made my first application with it, but I need multiple pages html for my app, how I setup this in the python code that start the eel.init() and eel.start("index.html")?

**Comment by samuelhwilliams** [comment]
Hi @felipexlr50 - this is supported just fine. You put the page you want to start on into `eel.start`, then just make sure that a script tag for `eel.js` is present in all pages you build. It should "just work" 🤞 

Let us know how you get on!

**Comment by felipexlr50** [comment]
Thanks, that works

**Comment by programmer-himanshu** [comment]
> Hi @felipexlr50 - this is supported just fine. You put the page you want to start on into `eel.start`, then just make sure that a script tag for `eel.js` is present in all HTML pages you build. It should "just work" 🤞
> 
> Let us know how you get on!

How can I close the previous window that was opened

**Comment by programmer-himanshu** [comment]
I got solution for this, to use multiple pages you just have use this little javascript function i.e  `window.location = "new.html"`  and must include **eel.js** in your html file

**Comment by maplepy** [comment]
does not work if parameter close_callback exists
