### ISSUE TITLE
JS sometimes fails to call Python functions while running

### ISSUE THREAD

**Issue by lingxiaohai** [samuelhwilliams/Eel#341]
There is a probability that JS can't send a message to Python

**Comment by samuelhwilliams** [comment]
It would be helpful to have some more information about this - could you share some code that exhibits the issue?

**Comment by lingxiaohai** [comment]
Closing the Electron CMD window will not automatically close

**Comment by samuelhwilliams** [comment]
I'm sorry, I don't understand the problem you're having. It's hard to help.

If you share your code, error messages, and screenshots, it will be easier to help you.
