### ISSUE TITLE
Compile to Exe not working

### ISSUE THREAD

**Issue by asdat3** [samuelhwilliams/Eel#342]
**Eel version**
Please state the version of Eel you're using.
0.11.0

**Describe the bug**
When I compile my Scipt to an Exe, I am getting an Error: "eel.js not found"
I am getting the error when I am trying to launch the Exe/packaged app
I am packing via auto-py-to-exe (master) (pyinstaller)
![blabla](https://user-images.githubusercontent.com/29544382/86413538-bdf6ce80-bcc1-11ea-8310-a4b39d089684.PNG)

**Imports in Python Script**
`import typing, datetime, discord, os, time, eel
from discord.ext import commands, tasks
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys`

**OS**
OS: Windows
Python ver: 3.7.8

**Comment by samuelhwilliams** [comment]
Can you include the command you're running to package the script please?

Do you get this error when you're packaging or when you're executing the packaged app?

**Comment by asdat3** [comment]
I am getting the error when I am trying to launch the Exe/packaged app

I am packing via auto-py-to-exe (master) (pyinstaller)

**Comment by asdat3** [comment]
python -m eel main.py web is printing a success, starting the exe isnt working(doesnt show anything) and I get a war-license_client.txt with loads of modules that are missing

**Comment by asdat3** [comment]
https://github.com/samuelhwilliams/Eel/issues/255#issuecomment-597466170
I guess it´s the same issue and he could fix it with this solution, but I dont know what he means with:
"refer to eel's readme" and how to do that

just an Idea

**Comment by samuelhwilliams** [comment]
There's a section about how to package Eel apps using pyinstaller here: https://github.com/samuelhwilliams/Eel#building-distributable-binary-with-pyinstaller.

It's titled "Building distributable binary with PyInstaller"

**Comment by samuelhwilliams** [comment]
I think the problem probably stems from using auto-py-to-exe. I haven't used that personally - but it might be missing some of the options that are needed which the above guide directs you to use.

**Comment by asdat3** [comment]
I dont get step 5
sorry

**Comment by samuelhwilliams** [comment]
You might want to read up on the PyInstaller docs here: http://pyinstaller.readthedocs.io/en/stable/

I'm sorry this is difficult at the moment. We've added a hook to PyInstaller that should make it easier to package Eel in the future, but we're waiting for them to release a newer version that includes our changes.

**Comment by asdat3** [comment]
There is nothing about excluding there
I still don´t get how to do it

**Comment by RahulBadenkal** [comment]
Jus to check, can you go to your exe folder and see if there is an eel folder present with a file called eel.js?
![image](https://user-images.githubusercontent.com/30529904/86448649-ae649d80-bd34-11ea-94eb-79451ca14634.png)

**Comment by asdat3** [comment]
no there is no folder

**Comment by asdat3** [comment]
![blabla2](https://user-images.githubusercontent.com/29544382/86449221-2a9cb800-bd18-11ea-8d3c-24deaeb8351a.PNG)

**Comment by RahulBadenkal** [comment]
Try copying the folder manually (I think it is in site packages/eel or something) to this directory and run the exe again to see if it works

**Comment by asdat3** [comment]
where to find it?

**Comment by asdat3** [comment]
![sdasdasawdawdasdawdaw](https://user-images.githubusercontent.com/29544382/86455296-b3b7ed00-bd20-11ea-838d-a50fa57a7369.PNG)
is this the content of your eel folder too?

**Comment by asdat3** [comment]
error is still there(eel.js not found)

**Comment by asdat3** [comment]
My output folder: (program is named "license_client")
![asdfiujdsfiusdfuiuhifuhief](https://user-images.githubusercontent.com/29544382/86455893-91729f00-bd21-11ea-92ef-3a646365a1c6.PNG)

I am using -in one file
since when I am using -in one directory and I try to open up the Exe, nothing happens at all

**Comment by RahulBadenkal** [comment]
Can you copy the eel folder inside licence cert folder.

**Comment by asdat3** [comment]
did already, but in this folder the Exe wont start at all

**Comment by asdat3** [comment]
OMG, it is working, thank you both so much <3
I wish you a wonderful day
