### ISSUE TITLE
Can't call a js function from a python process

### ISSUE THREAD

**Issue by WMoraes13** [samuelhwilliams/Eel#345]
Why when i call a a js function from a python process the function is not called? i'm starting a new process using multiprocess and at some point of the program the js function is called but nothing happends.

the python process call a js function passing a message as argument, this message needs to be displayed in the gui window, but for some reason the js function is not called.

I dont know what i'm missing here... Can anyone help me in this?

**Code snippet(s)**
Here is some code that can be easily used to reproduce the problem or understand what I need help with.

- [x] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

```python
import eel

...
```

```html
<html>
   ...
</html>
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by samuelhwilliams** [comment]
Please share some code that reproduces the issue - otherwise I'm afraid I won't be able to help you very much.

I haven't tested how Eel performs under a multiprocessing setup, but you will probably need to make sure that only the main Eel process is calling JS functions.

**Comment by WMoraes13** [comment]
> Please share some code that reproduces the issue - otherwise I'm afraid I won't be able to help you very much.
> 
> I haven't tested how Eel performs under a multiprocessing setup, but you will probably need to make sure that only the main Eel process is calling JS functions.

I've been testing it and when i use threads instead multiprocess the js function is called. The problem is that i need to use Multiprocessing....

**Comment by samuelhwilliams** [comment]
Then you'll need to pass any data required back from your worker processes to the main Eel process, which can then call the JS functions to pass data to the front end.

I'm going to close this now as I think I've pointed you in the direction you need to go, and there isn't much other directly-Eel-related advice to provide.
