### ISSUE TITLE
How to access local resources?

### ISSUE THREAD

**Issue by paragpv** [samuelhwilliams/Eel#356]
I'm trying to build an application which has a feature to display and edit content from local text files. 
I have a function to extract text from a file inside the directory '/web/docs' and load into a <textarea> (No directory given in snippet below). The text files inside the docs directory are generated by a python function.
The files load when I run the application through IDLE, but after I package it, my current approach won't work since there is no web/docs directories. I tried to create a folder in the same directory as the executable package, but access to external resources are not allowed. Is there a work around to have access to external files or atleast access to a file in the root directory of the executable? I tried the chrome flag **allow-file-access-from-files** and **--disable-web-security** with no success. Any help is appreciated.

```js

function setoutput() {
    document.getElementById("source_iframe").src = "Test.pdf";
    var xmlhttp, text;
    xmlhttp = new XMLHttpRequest();
    xmlhttp.open('GET', 'http://localhost:8000/Test.txt', false);
    xmlhttp.send();
    text = xmlhttp.responseText;
    document.getElementById("dest_frame").innerHTML = text;
}
```

```html
<html>
  <div  class="row editor-window">
    <div class="col-sm" id="source_file_view">
      <iframe src="about:blank" id="source_iframe"></iframe>
    </div>
     <div class="col-sm" id="feature_file_view">
        <textarea id="dest_frame"></textarea>
     </div>
</div>
</html>
```

 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by samuelhwilliams** [comment]
You probably want to be doing the file operations on the Python side, which can access the file system more easily/at all.

This example might help: https://github.com/samuelhwilliams/Eel/tree/master/examples/04%20-%20file_access

Does that point you in the right direction?

**Comment by paragpv** [comment]
> You probably want to be doing the file operations on the Python side, which can access the file system more easily/at all.

The file operations are being done on the Python side, but I'd like to display the processed files inside the UI. All the processed files are stored in a directory. The issue is that everything works well before packaging, because my directory is in localhost. After packaging, I can't find a way to put my processed files in a folder and then display them through the UI, because the root of the executable file is not in localhost and all external resources are blocked.

**Comment by RahulBadenkal** [comment]
"but access to external resources are not allowed" -> But since you are accessing files from withing the web/docs directory and web directory is the websites base directory, I think it should work fine.

**Comment by MrPinkX** [comment]
Did you find a solution?
