### ISSUE TITLE
How to close the Browser window from my code

### ISSUE THREAD

**Issue by chiragasawa** [samuelhwilliams/Eel#359]
I am using window.close() in my other javascript file to close the eel window when a button is clicked but it showing me some error which says "Maximum call stack size exceeded". Please help me for this problem

**Comment by samuelhwilliams** [comment]
Please can you share code from your Python and Javascript files, thanks.

**Comment by samuelhwilliams** [comment]
I'm going to close this as I assume you worked out what was wrong. :)
