### ISSUE TITLE
Edge isn't passed any arguments?

### ISSUE THREAD

**Issue by Nama** [samuelhwilliams/Eel#366]
I have the chromium based edge and wanted to use `--app` without modifying (#251)  `edge.py` and did `cmdline_args='--app=http://localhost:80/index.html'`, also `cmdline_args=['--app=http://localhost:80/index.html']`, but these didn't have any effect.

If I'm reading right, `options` isn't passed here:
https://github.com/samuelhwilliams/Eel/blob/e6db3f04ccf35893f963f96b282262a3218ba827/eel/edge.py#L9

**Comment by KyleKing** [comment]
I think I found that for legacy Edge, the [start command](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) would fail if passed options (https://github.com/samuelhwilliams/Eel/commit/f337af01b1bbcd292a3e5c85e0efc600939f608c). I would like to confirm, but I don't have access Windows right now. If the option flags do work, they should definitely be added to #251

**Comment by Nama** [comment]
Oh ya, I tested it on another machine, it really fails. And executing the exe directly isn't possible. What a bummer.
Thanks.

**Comment by Avaray** [comment]
It would be great if anyone will fix it.
