### ISSUE TITLE
Possibility to use PyArmor with Eel?

### ISSUE THREAD

**Issue by JanStgmnn** [samuelhwilliams/Eel#391]
**My problem:**
I'm currently adding a UI to my python project. I tested a bunch of libraries and found Eel is really really nice!
I got a project, that I compile as an .exe, and sadly I found out I am able to extract the code from the .exe with some tools.

I found PyArmor, which can obfuscate python code using PyInstaller. I could not find a way to use both PyArmor and Eel to build a standalone application.
If there is a way could you guys help me out?
If not, turn this into a feature request ;D

I can't provide any code, because I need my project to be private. But this problem should be fixeable without code snippets, if its fixeable in general.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Chrome Version: 85

**Comment by hiancdtrsnm** [comment]
`Eel` uses `pyinstaller` same as `pyarmor pack` maybe yo can pass the same option that eel uses with pyinstaller with pyarmor pack

**Comment by JanStgmnn** [comment]
Yeah I thought about that too.
But how does eel add the folder to the executable.

I couldn't find anything in the pyinstaller docs.

**Comment by hiancdtrsnm** [comment]
https://github.com/samuelhwilliams/Eel/blob/8e5e90e102a23dce8ad5200bf6b3ec60cde92b3b/eel/__main__.py#L31

in that file is all you need to know, in that line is when they set the parameter for the web folder

**Comment by JanStgmnn** [comment]
That's exactly what I needed.
Thank you so much!
