### ISSUE TITLE
Redirecting to a different page

### ISSUE THREAD

**Issue by MatthyPlayz** [samuelhwilliams/Eel#394]
**Describe the problem**
I'm trying to make my Eel application be able to have multiple pages and not just be one HTML file.
How can I redirect the application to another HTML file?

**Code snippet(s)**
Here is some code that can be easily used to reproduce the problem or understand what I need help with.

- [x] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

```python
import eel

# Set web files folder
eel.init('web')

eel.start('file1.html')
... file 1:
```

```html
<button onclick="window.location.href = 'file2.html'>file two</button>
```
... file 2:

``` html
<p>hello world!</p>
```

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 0.14.0?

**Comment by samuelhwilliams** [comment]
Your example works just fine, in principle, except you're missing a closing double-quote for the `onclick` attribute. It should be:

```html
<button onclick="window.location.href = 'file2.html'">file two</button>
```

Eel presents as a standard webserver using basic HTML/CSS/JS, so you don't need to do anything unusual to support moving between pages in your app.

**Comment by MatthyPlayz** [comment]
That was just an example, and I need to have it in a JavaScript `submit()` function, and the `window.location.href = 'file2.html'` snippet does not work

**Comment by MatthyPlayz** [comment]
Seems that adding one slash before the `file2.html` worked!
Thanks for your help
