### ISSUE TITLE
How to assign a returning variable in js to a python variable.

### ISSUE THREAD

**Issue by sameera-madushan** [samuelhwilliams/Eel#398]
Hey! I have a js function like this. How can i assign this returning sec variable into a python variable. I tried to pass this into a python function with an argument but i can't recall the function. any help would be appreciated. Thanks. 
![2020-10-04_091755](https://user-images.githubusercontent.com/55880211/95009805-6b230f00-0642-11eb-8f94-296ec2ce68f1.png)

**Comment by sameera-madushan** [comment]
Found a solution. Closing the isuue.

**Comment by samuelhwilliams** [comment]
Hey - think I'm helping you on Discord now, but to give a general reply, I think example 01 - hello world is basically all you need to get going with this.

**Comment by sameera-madushan** [comment]
Thanks. I'll try again.
