### ISSUE TITLE
No module name error while building distributable file

### ISSUE THREAD

**Issue by MK096** [samuelhwilliams/Eel#399]
Whenever i use "cexprtk " package in python my program executes smoothly but whenever i try to build a distributable exe file it throws me a module not find error (in cmd) due to which the program doesn't execute
![cex](https://user-images.githubusercontent.com/20142735/96162711-4c6e2380-0f32-11eb-95fc-5401fef0a7a9.PNG)

**Comment by samuelhwilliams** [comment]
This sounds like PyInstaller can't find `cexprtk` - please refer to their docs on how to include it: https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#listing-hidden-imports

Please let us know if this solves your issue :) We mention this in our readme but maybe it's not clear enough.

**Comment by MK096** [comment]
Also,  when i try to build exe it throws an error "can't find the xyz.txt file". (This only happens when i try to build an exe ...When i compile my program in python IDLE this doesn't happen)
![form](https://user-images.githubusercontent.com/20142735/96287228-09c44e00-0ffb-11eb-88b4-3aee351812ef.PNG)

**Comment by samuelhwilliams** [comment]
You'll need to look into PyInstaller to work out how to tell it that it needs to collect extra files your program expects to exist, e.g. `formula.txt`. From memory this would be something like adding the option `--data-file formula.txt`.
