### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found) eel.js:1

### ISSUE THREAD

**Issue by DARKDRAGON532** [samuelhwilliams/Eel#405]
**Describe the problem**
Javascript cant find eel.js

**Code snippet(s)**
Here is some code that can be easily used to reproduce the problem or understand what I need help with.

- [ X] I know that if I don't provide sample code that allows someone to quickly step into my shoes, I may not get the help I want or my issue may be closed.

```
<script type="text/javascript" src="/eel.js"></script>
```

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macosx
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] python 3.9

**Comment by samuelhwilliams** [comment]
Sorry, there's not enough information here to help you. Please provide more of your code, or refer to the examples and see how your own code differs.
