### ISSUE TITLE
Exposin my EEL app to the web

### ISSUE THREAD

**Issue by binarioGH** [samuelhwilliams/Eel#408]
**I want other people to use my app on my local network without installing anything.**
I know that EEL executes on localhost on port 8000, and i have been using SSH tunneling to expose it to other people, but it would be way easier if there was a function or method which would let me bind EEL to my local IP.

**Comment by samuelhwilliams** [comment]
This should already be possible. You can set `host` to `0.0.0.0` in `eel.start`. Let me know if that doesn't work?
