### ISSUE TITLE
Bring Window to Foreground or Set to Topmost Window

### ISSUE THREAD

**Issue by aibharata** [samuelhwilliams/Eel#419]
Is there a way to keep the eel application on top of all other open windows.

**Desktop :**
 - OS: Windows 7
 - Browser: Chrome

**Comment by samuelhwilliams** [comment]
This is probably an exercise for the developer. It may be configurable on a per-browser basis, but it doesn't feel like something for Eel to control. Try having a look at Chrome's command-line flags to see if there's one that keeps the window on top. If there is, you can apply it through the `cmdline_args` argument to `eel.start`
