### ISSUE TITLE
Parsing eel.expose calls doesn't respect the name param

### ISSUE THREAD

**Issue by kpwelsh** [samuelhwilliams/Eel#69]
Parsing the eel.expose calls from the js files doesn't respect the name parameter. It grabs all thats inside of the call and tries to assign a lambda function to that, which results in things like:

`function, 'myFunction' = lambda...`

This is annoying, because it makes anything more than trivial function labels impossible to use - in typescript:
```
class TestClass {
    constructor () {
        eel.serverPrint('Hello from the client!')
        eel.expose(this.consolePrint, 'consolePrint')
    }

    consolePrint(s : string) {
        console.log('Message from server:' + s);
    }
}
```

this fails on both assigning a value to this.consolePrint and 'consolePrint.'

Ima just hack this in to a local branch. It does seem like there is a better way to do this whole part, though.
```
eel.init(path):
  ...
                        if ',' in expose_call:
                            expose_call = expose_call.split(',')[1]
                        expose_call = expose_call.strip().strip('\'')
  ...
```

**Comment by ChrisKnott** [comment]
@Kevdog25 

This whole part is like the shameful secret of the module... I racked my brain trying to think of an elegant solution. The main issue is that we have to, to some extent "understand" the Javascript code, from the Python side, _before the Javascript engine is running_. We want python code that calls `eel.some_js_method_name()` to not crash. I think this requires some kind of static analysis of the code, but the current static analysis is incredibly naive. 

Ideally you should be able to do something like this (naming an anonymous function);
```javascript
eel.expose(
    function(x){
        // this comment could contain anything ,.()#@!
        return x + 1;
    },
    // another comment for good luck ,,,,
    'some_js_method_name'
);
```

I don't think I am going to have a chance to work on eel for a while but I am very happy to accept PRs or ideas for how to achieve this.

**Comment by ghostzero192** [comment]
@ChrisKnott  first and foremost great library it is just what i was looking for, i tried what you suggested 
`eel.expose(function(x){return x + 1;},'my_func');`
and python show this error:  **AttributeError: module 'eel' has no attribute 'my_func'** 
by the way i'm using windows

**Comment by ghostzero192** [comment]
@Kevdog25 i double checked my code an i had an identation issue thanks
