### ISSUE TITLE
Exe file 'distribution not found'

### ISSUE THREAD

**Issue by IvoLanjouw** [samuelhwilliams/Eel#72]
When I was testing if I had any trouble compiling the examples, I already ran into a problem.
When comiling the 'sync_callbacks' example this happens when I run the exe:
https://dl.dropboxusercontent.com/s/x4qpuurck9gqcaf/2018-09-18_14-58-15.mp4

I doesnt always show the same error, 
sometimes it says 
'The 'cffi>=1.11.5' distribution was not found and is required by the application'
or
'The 'greenlet>=0.4.14' distribution was not found and is required by the application'

**Comment by ChrisKnott** [comment]
This is possibly a conflict between Anaconda and gevent's monkey patching. Does it work for you on plain CPython3?
