### ISSUE TITLE
not allowed to load local resource

### ISSUE THREAD

**Issue by rakakhrl** [samuelhwilliams/Eel#76]
i keep getting this error in chrome dev-tools, i know that this problem can be solved with creating a local server bcs browser can't directly access your local files for security reason. But when eel app is running it runs on a local server, so why this error keep showing?

**Comment by ChrisKnott** [comment]
@rakakhrl yes, the whole point of the library is to avoid this... I need to know a bit more about your code to see what is going on. I've not seen this issue before

**Comment by samuelhwilliams** [comment]
Hi @rakakhrl. I'm closing this off for now based on inactivity. Please drop a message if you still need help.

**Comment by Iftakharpy** [comment]
# Not allowed to load local resource: file:///D:/YoutubeDownloader/gui/web/main.js
I am getting the same error now and javascript file is not loading to the app window.
![Capture](https://user-images.githubusercontent.com/37600593/91650912-ab252e00-eaa7-11ea-9229-30a2ddb432ee.PNG)

**Comment by MrPinkX** [comment]
This. Isn't there a way to get javascript access local files like Electron offers?
