### ISSUE TITLE
Implement routing

### ISSUE THREAD

**Issue by ssekuwanda** [samuelhwilliams/Eel#81]
Thanks @ChrisKnott for the awesome project, Has any body implemented flask-like routing. This is the next missing link since @sandars41 helped with jinja templates

**Comment by ahopkins** [comment]
Might I suggest looking at [`xrtr`](
https://github.com/vltr/xrtr) from @vltr? Incredibly fast and configurable. Still some performance enhancements coming, but I am pretty sure the API is stable.

**Comment by vltr** [comment]
Thanks spreading the word on `xrtr`, @ahopkins ! It may lack Windows / macOS binary builds (for now, since it's written in Cython), but I think this will be fixed at the end of the year _at most_ :+1:

**Comment by samuelhwilliams** [comment]
This isn't something we're considering at the moment (obvious given the lack of attention - sorry), so I'm going to close this for now. But if you're really keen on this then please do consider opening a new issue with some more thoughts around it - specifically around your use case and maybe some ideas on how it could work.

Thanks!
