### ISSUE TITLE
Eel for web applications ?

### ISSUE THREAD

**Issue by brumar** [samuelhwilliams/Eel#85]
I did not tried to use Eel for web applications but that seems possible right ? Do you see problems or limitations ?
Of course this is the opposite goal of eel, but still, the exposing mechanisms are so sweet that one could want to use Eel for web development too.

**Comment by 04fsnape** [comment]
Probably best to use [Flask](http://flask.pocoo.org/).

**Comment by PenguinxEnjoi** [comment]
I am wanting to do the same thing. Maybe use Eel to run the app on your local host and then use Ngrok to expose your local host to the web and now your local app is a web app?? Profit? Success?

**Comment by samuelhwilliams** [comment]
Hi both. I don't think this is a use-case I'm keen to support for Eel at the moment, so I'm going to close this off for now. Sorry, but hopefully you can still see lots of value in what Eel is mainly targetted at.
